; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lv_support
src_dir = src
boards_dir = ./boards
[env]
platform = espressif32@6.4.0
board = lilygo-t-displays3
framework = arduino
debug_tool = esp-builtin
upload_protocol = esptool
build_flags = 
	-I=../../src/
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DARDUINO_USB_MODE=1
	-DTOUCH_MODULES_CST_MUTUAL
	-DPRINT_DEBUG_MESSAGES=1

[env:lv_support]
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
build_flags = ${env.build_flags}
lib_ignore = 
	TFT_eSPI
	GFX Library for Arduino
	arduino-nofrendo
	Adafruit MPR121
	DabbleESP32
	PCF8575 library
	PCA95x5
lib_deps = 
	lvgl/lvgl@8.3.6
;	esphome/ESPAsyncWebServer-esphome @ ^3.0.0
;  	me-no-dev/AsyncTCP @ ^1.1.1
	ESP Async WebServer
	michalmonday/CSV Parser@^1.4.1
	bblanchon/ArduinoJson@^7.4.2
