#include "OptionsModel.h"
#include "SysOptions.h"

/**
 * @brief The descriptor table definition.
 *
 * This table drives the entire options management system. You must add an
 * entry here for every single option in your sysOptions struct.
 *
 * Format: { "CSV_Option_Name", TYPE, offsetof(sysOptions, struct_member), size_for_strings }
 */
const OptionDescriptor optionDescriptors[] = {
    {"ADC_VbattCorr",        TYPE_FLOAT,  offsetof(sysOptions, ADC_VbattCorr), 0},
    {"ADC_VmeasR1NegGain",   TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR1NegGain), 0},
    {"ADC_VmeasR1NegOffset", TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR1NegOffset), 0},
    {"ADC_VmeasR2NegGain",   TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR2NegGain), 0},
    {"ADC_VmeasR2NegOffset", TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR2NegOffset), 0},
    {"ADC_VmeasR1Offset",    TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR1Offset), 0},
    {"ADC_VmeasR1PosGain",   TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR1PosGain), 0},
    {"ADC_VmeasR1PosOffset", TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR1PosOffset), 0},
    {"ADC_VmeasR2Offset",    TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR2Offset), 0},
    {"ADC_VmeasR2PosGain",   TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR2PosGain), 0},
    {"ADC_VmeasR2PosOffset", TYPE_FLOAT,  offsetof(sysOptions, ADC_VmeasR2PosOffset), 0},
    {"ADC_VrefGain",         TYPE_FLOAT,  offsetof(sysOptions, ADC_VrefGain), 0},
    {"ADC_VrefOffset",       TYPE_FLOAT,  offsetof(sysOptions, ADC_VrefOffset), 0},
    {"ADC_x2_GainCorr",      TYPE_FLOAT,  offsetof(sysOptions, ADC_x2_GainCorr), 0},
    {"ADC_x4_GainCorr",      TYPE_FLOAT,  offsetof(sysOptions, ADC_x4_GainCorr), 0},
    {"ADC_x8_GainCorr",      TYPE_FLOAT,  offsetof(sysOptions, ADC_x8_GainCorr), 0},
    {"ADC_x16_GainCorr",     TYPE_FLOAT,  offsetof(sysOptions, ADC_x16_GainCorr), 0},
    {"ADC_x32_GainCorr",     TYPE_FLOAT,  offsetof(sysOptions, ADC_x32_GainCorr), 0},
    {"ADC_x64_GainCorr",     TYPE_FLOAT,  offsetof(sysOptions, ADC_x64_GainCorr), 0},
    {"ADC_x128_GainCorr",    TYPE_FLOAT,  offsetof(sysOptions, ADC_x128_GainCorr), 0},
    {"BattLowThreshold",     TYPE_FLOAT,  offsetof(sysOptions, BattLowThreshold), 0},
    {"BattOkThreshold",      TYPE_FLOAT,  offsetof(sysOptions, BattOkThreshold), 0},
    {"DAC_V_Iref_Gain",      TYPE_FLOAT,  offsetof(sysOptions, DAC_V_Iref_Gain), 0},
    {"DAC_V_Iref_Offset",    TYPE_FLOAT,  offsetof(sysOptions, DAC_V_Iref_Offset), 0},
    {"DAC_V_Iset_Gain",      TYPE_FLOAT,  offsetof(sysOptions, DAC_V_Iset_Gain), 0},
    {"DAC_V_Iset_Offset",    TYPE_FLOAT,  offsetof(sysOptions, DAC_V_Iset_Offset), 0},
    {"DAC_Voffs_Gain",       TYPE_FLOAT,  offsetof(sysOptions, DAC_Voffs_Gain), 0},
    {"DAC_Voffs_Offset",     TYPE_FLOAT,  offsetof(sysOptions, DAC_Voffs_Offset), 0},
    {"DAC_Vsetn_Gain",       TYPE_FLOAT,  offsetof(sysOptions, DAC_Vsetn_Gain), 0},
    {"DAC_Vsetn_Offset",     TYPE_FLOAT,  offsetof(sysOptions, DAC_Vsetn_Offset), 0},
    {"DAC_Vsetp_Gain",       TYPE_FLOAT,  offsetof(sysOptions, DAC_Vsetp_Gain), 0},
    {"DAC_Vsetp_Offset",     TYPE_FLOAT,  offsetof(sysOptions, DAC_Vsetp_Offset), 0},
    {"Diode_I_LED",          TYPE_FLOAT,  offsetof(sysOptions, Diode_I_LED), 0},
    {"Diode_I_LowVF",        TYPE_FLOAT,  offsetof(sysOptions, Diode_I_LowVF), 0},
    {"Diode_I_Zener",        TYPE_FLOAT,  offsetof(sysOptions, Diode_I_Zener), 0},
    {"Diode_V_LED",          TYPE_FLOAT,  offsetof(sysOptions, Diode_V_LED), 0},
    {"Diode_V_LowVF",        TYPE_FLOAT,  offsetof(sysOptions, Diode_V_LowVF), 0},
    {"Diode_V_Zener",        TYPE_FLOAT,  offsetof(sysOptions, Diode_V_Zener), 0},
    {"Ohm_I_1R",             TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_1R), 0},
    {"Ohm_I_1kR",            TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_1kR), 0},
    {"Ohm_I_10kR",           TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_10kR), 0},
    {"Ohm_I_100kR",          TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_100kR), 0},
    {"Ohm_I_1MR",            TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_1MR), 0},
    {"Ohm_I_10MR",           TYPE_FLOAT,  offsetof(sysOptions, Ohm_I_10MR), 0},
    {"Ohm_V_1R",             TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_1R), 0},
    {"Ohm_V_1kR",            TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_1kR), 0},
    {"Ohm_V_10kR",           TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_10kR), 0},
    {"Ohm_V_100kR",          TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_100kR), 0},
    {"Ohm_V_1MR",            TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_1MR), 0},
    {"Ohm_V_10MR",           TYPE_FLOAT,  offsetof(sysOptions, Ohm_V_10MR), 0},
    {"SMU_I_Lim",            TYPE_FLOAT,  offsetof(sysOptions, SMU_I_Lim), 0},
    {"SMU_V_Lim",            TYPE_FLOAT,  offsetof(sysOptions, SMU_V_Lim), 0},
    {"BattProtect",          TYPE_BOOL,   offsetof(sysOptions, BattProtect), 0},
    {"Diode_MeasMode",       TYPE_BOOL,   offsetof(sysOptions, Diode_MeasMode), 0},
    {"Diode_Buzz",           TYPE_BOOL,   offsetof(sysOptions, Diode_Buzz), 0},
    {"Ohm_Buzz",             TYPE_BOOL,   offsetof(sysOptions, Ohm_Buzz), 0},
    {"Ohm_MeasMode",         TYPE_BOOL,   offsetof(sysOptions, Ohm_MeasMode), 0},
    {"Opt_FlipScreen",       TYPE_BOOL,   offsetof(sysOptions, Opt_FlipScreen), 0},
    {"SleepWithCharger",     TYPE_BOOL,   offsetof(sysOptions, SleepWithCharger), 0},
    {"TimeDaylightOffset",   TYPE_BOOL,   offsetof(sysOptions, TimeDaylightOffset), 0},
    {"ADC_Averages",         TYPE_UINT16, offsetof(sysOptions, ADC_Averages), 0},
    {"ADC_Sample_Rate",      TYPE_UINT16, offsetof(sysOptions, ADC_Sample_Rate), 0},
    {"ADC_VdiffGain",        TYPE_UINT16, offsetof(sysOptions, ADC_VdiffGain), 0},
    {"ADC_VnPGain",          TYPE_UINT16, offsetof(sysOptions, ADC_VnPGain), 0},
    {"BacklightBrightness",  TYPE_UINT16, offsetof(sysOptions, BacklightBrightness), 0},
    {"BacklightLowBrght",    TYPE_UINT16, offsetof(sysOptions, BacklightLowBrght), 0},
    {"BacklightTout",        TYPE_UINT16, offsetof(sysOptions, BacklightTout), 0},
    {"BattMinChargeLeft",    TYPE_UINT16, offsetof(sysOptions, BattMinChargeLeft), 0},
    {"DiodeType",            TYPE_UINT16, offsetof(sysOptions, DiodeType), 0},
    {"LastScreen",           TYPE_UINT16, offsetof(sysOptions, LastScreen), 0},
    {"Ohm_Range",            TYPE_UINT16, offsetof(sysOptions, Ohm_Range), 0},
    {"Revision",             TYPE_UINT16, offsetof(sysOptions, Revision), 0},
    {"SleepMaxTime",         TYPE_UINT16, offsetof(sysOptions, SleepMaxTime), 0},
    {"SleepNumCyclesToMeas", TYPE_UINT16, offsetof(sysOptions, SleepNumCyclesToMeas), 0},
    {"SleepTimeCycleMs",     TYPE_UINT16, offsetof(sysOptions, SleepTimeCycleMs), 0},
    {"StandbyTout",          TYPE_UINT16, offsetof(sysOptions, StandbyTout), 0},
    {"SwitchTurnOffTime",    TYPE_UINT16, offsetof(sysOptions, SwitchTurnOffTime), 0},
    {"Volt_Range",           TYPE_UINT16, offsetof(sysOptions, Volt_Range), 0},
    {"TimeZone",             TYPE_INT16,  offsetof(sysOptions, TimeZone), 0},
    {"MAC_Address_Device",   TYPE_STRING, offsetof(sysOptions, MAC_Address_Device), sizeof(sysOptions::MAC_Address_Device)},
    {"MAC_Address_Remote",   TYPE_STRING, offsetof(sysOptions, MAC_Address_Remote), sizeof(sysOptions::MAC_Address_Remote)},
};

const size_t numOptionDescriptors = sizeof(optionDescriptors) / sizeof(optionDescriptors[0]);