// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef _SIMPLEESP32S3_UI_H
#define _SIMPLEESP32S3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Main.h"
#include "screens/ui_WiFi.h"
#include "screens/ui_Graph.h"
#include "screens/ui_Volt_More.h"
#include "screens/ui_MoreOptions.h"
#include "screens/ui_Messages.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * KeybOffAn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * KeybOnAn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * KeybNumOnAn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * KeybNumOffAn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bargraph_24fs_png);    // assets/Bargraph_24FS.png
LV_IMG_DECLARE(ui_img_speakerofficon_png);    // assets/SpeakerOffIcon.png
LV_IMG_DECLARE(ui_img_speakeronicon_png);    // assets/SpeakerOnIcon.png
LV_IMG_DECLARE(ui_img_icn_pc_png);    // assets/icn_pc.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_chargein_png);    // assets/ChargeIn.png

// FONTS
LV_FONT_DECLARE(ui_font_Lucon48);
LV_FONT_DECLARE(ui_font_SegD22);
LV_FONT_DECLARE(ui_font_SegD48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
