// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SimpleESP32S3
#include "ui.h"
#include "DiffAmp.h"
#include "PCA9554.h"
#include "SysOptions.h"
extern sysOptions sysOpt;
extern vi_limits ohm_vi_Limits;
extern vi_limits diode_vi_Limits;
extern bool uiActions;
extern vi_limits initUI_OhmData(sysOptions* sysOpt, uint16_t range);
extern vi_limits initUI_DiodeData(sysOptions* sysOpt, uint16_t range);

void ChangeMaxBrightness(lv_event_t * e)
{
	uint16_t curr_brightness;
	char txtd[25];
	curr_brightness = lv_slider_get_value(ui_MaxBrightnessCtrl);
	sysOpt.BacklightBrightness = curr_brightness;
	curr_brightness = curr_brightness * BL_PWM_RES / lv_slider_get_max_value(ui_MaxBrightnessCtrl);
	ledcWrite(BL_PWM, curr_brightness);
	curr_brightness = curr_brightness * 100 / BL_PWM_RES ; // Scaled value to 0 to 100% range to display
	sprintf(txtd, "Brightness: [%d%%]", curr_brightness);
	lv_label_set_text(ui_MaxBrightnessLbl, txtd);
	uiActions = true;
}

void ChangeMinBrightness(lv_event_t * e)
{
	// Your code here
	uint16_t curr_brightness;
	char txtd[25];
	curr_brightness = lv_slider_get_value(ui_MinBrightnessCtrl);
	sysOpt.BacklightLowBrght = curr_brightness;
	sprintf(txtd, "LP Brightness: [%d%%]", curr_brightness);
	lv_label_set_text(ui_MinBrightnessLbl, txtd);
	uiActions = true;
}

void ChangeBacklightTout(lv_event_t * e)
{
	// Your code here
	uint16_t Timeout;
	char txtd[25];
	Timeout = lv_slider_get_value(ui_BacklightToutCtrl);
	sysOpt.BacklightTout = Timeout;
	if(Timeout == 0) 
		sprintf(txtd, "BL Timeout: [OFF]");
	else sprintf(txtd, "BL Timeout: [%d sec]", Timeout * 5);
	lv_label_set_text(ui_BacklightToutLbl, txtd);
	uiActions = true;
}

void FlipScreenFn(lv_event_t * e)
{
	// Your code here	
	sysOpt.Opt_FlipScreen = false;
	if(lv_obj_has_state(ui_FlipDispCntrl, LV_STATE_CHECKED)) {
		lv_disp_set_rotation(lv_disp_get_default(), LV_DISP_ROT_180);
		sysOpt.Opt_FlipScreen = true;
	}
	
	else 
		lv_disp_set_rotation(lv_disp_get_default(), LV_DISP_ROT_NONE);
	uiActions = true;
}

void ScanWiFiNetwork(lv_event_t * e)
{
	// Your code here
	//extern bool scanWiFiNetworks(char * ssid);
	bool test;
	char * ssid_in;
	lv_label_set_text(ui_WiFiStatusLbl, "Scanning for networks...");
	uiActions = true;
	//if (scanWiFiNetworks(ssid_in) == false){
	//	lv_label_set_text(ui_WiFiStatusLbl, "No networks found");
	//	return;
	//}
	//else {
	//	lv_label_set_text(ui_WiFiStatusLbl, "See SSID List");
	//	lv_dropdown_set_options(ui_SSIDList, ssid_in);
	//}
}

void ConnectWiFiNetwork(lv_event_t * e)
{
	// Your code here
	uiActions = true;
}
void SetVinDivider(lv_event_t * e)
{
	// Your code here
	bool state = lv_obj_has_state(ui_VinDividerBox, LV_STATE_CHECKED);
	setRelayDivider(state);
	uiActions = true;
}

void SetViffRangeFn(lv_event_t * e)
{
	// Your code here
	sysOpt.Volt_Range = lv_dropdown_get_selected(ui_VoltRangeDn);
	uiActions = true;
}

void SetOhmRangeFn(lv_event_t * e)
{
	// Your code here
	sysOpt.Ohm_Range = lv_dropdown_get_selected(ui_OhmSelDn);
	ohm_vi_Limits = initUI_OhmData(&sysOpt, sysOpt.Ohm_Range);
	uiActions = true;
}

void OhmSampleModeFn(lv_event_t * e)
{
	// Your code here
	if(lv_obj_has_state(ui_OhmModeCb, LV_STATE_CHECKED))
		sysOpt.Ohm_MeasMode = true;
	else
		sysOpt.Ohm_MeasMode = false;
	uiActions = true;	
}

void SetOhmBuzzFn(lv_event_t * e)
{
	// Your code here
	if(lv_obj_has_state(ui_OhmBuzzBtn, LV_STATE_CHECKED))
		sysOpt.Ohm_Buzz= true;
	else
		sysOpt.Ohm_Buzz = false;
	uiActions = true;	
}

void DiodeSampleModeFn(lv_event_t * e)
{
	// Your code here
	if(lv_obj_has_state(ui_DiodeMeasModeCb, LV_STATE_CHECKED))
		sysOpt.Diode_MeasMode = true;
	else
		sysOpt.Diode_MeasMode = false;
	uiActions = true;
}

void SetDiodeBuzzFn(lv_event_t * e)
{
	// Your code here
	if(lv_obj_has_state(ui_DiodeBuzzBtn, LV_STATE_CHECKED))
		sysOpt.Diode_Buzz= true;
	else
		sysOpt.Diode_Buzz= false;
	uiActions = true;	
}

void SetDiodeTypeFn(lv_event_t * e)
{
	// Your code here
	sysOpt.DiodeType = lv_dropdown_get_selected(ui_DiodeVfSelDn);
	diode_vi_Limits = initUI_DiodeData(&sysOpt, sysOpt.DiodeType);
	uiActions = true;
}

void SMU_V_SetFn(lv_event_t * e)
{
	// Your code here
	sysOpt.SMU_V_Lim = float (lv_spinbox_get_value(ui_VoltLimitSpin))/1000;
	uiActions = true;
}

void SMU_I_SetFn(lv_event_t * e)
{
	// Your code here
	sysOpt.SMU_I_Lim = float (lv_spinbox_get_value(ui_CurrLimitSpin))/1000;
	uiActions = true;
}

void StandbyModeFn(lv_event_t * e)
{
	// Your code here
	sysOpt.StandbyTout = lv_dropdown_get_selected(ui_StandbyOptDn);
	uiActions = true;
}

void SetTimeZoneFn(lv_event_t * e)
{
	// Your code here
	sysOpt.TimeZone = lv_dropdown_get_selected(ui_TimeZonesDn) - 12;
	uiActions = true;
}

void SetDaylightOffsetFn(lv_event_t * e)
{
	// Your code here
	sysOpt.TimeDaylightOffset = lv_obj_has_state(ui_DaylightCorrCb, LV_STATE_CHECKED);
	uiActions = true;
}


void SetVnP_GainFn(lv_event_t * e)
{
	// Your code here
	sysOpt.ADC_VnPGain = lv_dropdown_get_selected(ui_VprobeGainSelectDn);
	uiActions = true;
}

void SetVdiff_GainFn(lv_event_t * e)
{
	// Your code here
	sysOpt.ADC_VdiffGain = lv_dropdown_get_selected(ui_VdiffGainSelectDn);
	uiActions = true;
}

void SetADC_NumAvgFn(lv_event_t * e)
{
	// Your code here
	sysOpt.ADC_Averages = lv_dropdown_get_selected(ui_SampleAvgDn);
	uiActions = true;
}

void SetADC_SampleRateFn(lv_event_t * e)
{
	// Your code here
	sysOpt.ADC_Sample_Rate = lv_dropdown_get_selected(ui_SampleRateDn);
	uiActions = true;

}


void ResetTimeouts(lv_event_t * e)
{
	// Your code here
	uiActions = true;
}

void ResetFunctions(lv_event_t * e)
{
	// Your code here
}

void SetSleepMaxTime(lv_event_t * e)
{
	// Your code here
	char txtd[25];
	sysOpt.SleepMaxTime =lv_slider_get_value(ui_MaxSleepTimeCtrl);
	sprintf(txtd, "Max Time in Sleep [%dHr]", sysOpt.SleepMaxTime);
	lv_label_set_text(ui_MaxSleepTimeLbl, txtd);
  	

}

void SetSleepWithChargerOpt(lv_event_t * e)
{
	// Your code here
	sysOpt.SleepWithCharger = lv_obj_has_state(ui_KeepOnWithChargerCb, LV_STATE_CHECKED);
	
}


void SetBatteryProtectionOpt(lv_event_t * e)
{
	// Your code here
	sysOpt.BattProtect = lv_obj_has_state(ui_BatteryProtectionCb, LV_STATE_CHECKED);
}
