// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ResetTimeouts(lv_event_t * e);
void SetVinDivider(lv_event_t * e);
void SetViffRangeFn(lv_event_t * e);
void SetOhmRangeFn(lv_event_t * e);
void OhmSampleModeFn(lv_event_t * e);
void SetOhmBuzzFn(lv_event_t * e);
void SetDiodeTypeFn(lv_event_t * e);
void DiodeSampleModeFn(lv_event_t * e);
void SetDiodeBuzzFn(lv_event_t * e);
void SMU_V_SetFn(lv_event_t * e);
void SMU_I_SetFn(lv_event_t * e);
void FlipScreenFn(lv_event_t * e);
void StandbyModeFn(lv_event_t * e);
void ChangeMaxBrightness(lv_event_t * e);
void ChangeMinBrightness(lv_event_t * e);
void ChangeBacklightTout(lv_event_t * e);
void ScanWiFiNetwork(lv_event_t * e);
void ConnectWiFiNetwork(lv_event_t * e);
void SetVnP_GainFn(lv_event_t * e);
void SetVdiff_GainFn(lv_event_t * e);
void SetADC_SampleRateFn(lv_event_t * e);
void SetADC_NumAvgFn(lv_event_t * e);
void SetTimeZoneFn(lv_event_t * e);
void SetDaylightOffsetFn(lv_event_t * e);
void SetSleepMaxTime(lv_event_t * e);
void SetSleepWithChargerOpt(lv_event_t * e);
void SetBatteryProtectionOpt(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
