// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * ui_Graph = NULL;
lv_obj_t * ui_VoltChart = NULL;
lv_obj_t * ui_VdiffCb = NULL;
lv_obj_t * ui_VprobePCb = NULL;
lv_obj_t * ui_VdriveCb = NULL;
lv_obj_t * ui_IsenseCb = NULL;
lv_obj_t * ui_VprobeNCb = NULL;
lv_obj_t * ui_GraphRetBtn = NULL;
lv_obj_t * ui_GraphRetLbl = NULL;
// event funtions
void ui_event_GraphRetBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Graph_screen_init(void)
{
    ui_Graph = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Graph, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_Graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Graph, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Graph, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltChart = lv_chart_create(ui_Graph);
    lv_obj_set_width(ui_VoltChart, 239);
    lv_obj_set_height(ui_VoltChart, 148);
    lv_obj_set_x(ui_VoltChart, -15);
    lv_obj_set_y(ui_VoltChart, -8);
    lv_obj_set_align(ui_VoltChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_VoltChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_VoltChart, LV_CHART_AXIS_PRIMARY_Y, 0, 62);
    lv_chart_set_axis_tick(ui_VoltChart, LV_CHART_AXIS_PRIMARY_X, 5, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_VoltChart, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_VoltChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_VoltChart_series_1 = lv_chart_add_series(ui_VoltChart, lv_color_hex(0x0F06FA),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_VoltChart_series_1_array[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    lv_chart_set_ext_y_array(ui_VoltChart, ui_VoltChart_series_1, ui_VoltChart_series_1_array);
    lv_chart_series_t * ui_VoltChart_series_2 = lv_chart_add_series(ui_VoltChart, lv_color_hex(0xE40B0B),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_VoltChart_series_2_array[] = { 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 };
    lv_chart_set_ext_y_array(ui_VoltChart, ui_VoltChart_series_2, ui_VoltChart_series_2_array);
    lv_chart_series_t * ui_VoltChart_series_3 = lv_chart_add_series(ui_VoltChart, lv_color_hex(0x0CFA09),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_VoltChart_series_3_array[] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40 };
    lv_chart_set_ext_y_array(ui_VoltChart, ui_VoltChart_series_3, ui_VoltChart_series_3_array);
    lv_chart_series_t * ui_VoltChart_series_4 = lv_chart_add_series(ui_VoltChart, lv_color_hex(0xCC0FF3),
                                                                    LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_VoltChart_series_4_array[] = { 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60 };
    lv_chart_set_ext_y_array(ui_VoltChart, ui_VoltChart_series_4, ui_VoltChart_series_4_array);
    lv_chart_series_t * ui_VoltChart_series_5 = lv_chart_add_series(ui_VoltChart, lv_color_hex(0x09E1F8),
                                                                    LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_VoltChart_series_5_array[] = { 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80 };
    lv_chart_set_ext_y_array(ui_VoltChart, ui_VoltChart_series_5, ui_VoltChart_series_5_array);

    lv_obj_set_style_size(ui_VoltChart, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_VoltChart, lv_color_hex(0x030303), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_VdiffCb = lv_checkbox_create(ui_Graph);
    lv_checkbox_set_text(ui_VdiffCb, "Vdiff");
    lv_obj_set_width(ui_VdiffCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdiffCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiffCb, 132);
    lv_obj_set_y(ui_VdiffCb, -73);
    lv_obj_set_align(ui_VdiffCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VdiffCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_VdiffCb, lv_color_hex(0x1307F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VdiffCb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VprobePCb = lv_checkbox_create(ui_Graph);
    lv_checkbox_set_text(ui_VprobePCb, "VpP");
    lv_obj_set_width(ui_VprobePCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VprobePCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VprobePCb, 130);
    lv_obj_set_y(ui_VprobePCb, -53);
    lv_obj_set_align(ui_VprobePCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VprobePCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_VprobePCb, lv_color_hex(0xF5083B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VprobePCb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VdriveCb = lv_checkbox_create(ui_Graph);
    lv_checkbox_set_text(ui_VdriveCb, "Vdrv");
    lv_obj_set_width(ui_VdriveCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdriveCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdriveCb, 131);
    lv_obj_set_y(ui_VdriveCb, -12);
    lv_obj_set_align(ui_VdriveCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VdriveCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_VdriveCb, lv_color_hex(0xD412F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VdriveCb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_IsenseCb = lv_checkbox_create(ui_Graph);
    lv_checkbox_set_text(ui_IsenseCb, "Isns");
    lv_obj_set_width(ui_IsenseCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsenseCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IsenseCb, 129);
    lv_obj_set_y(ui_IsenseCb, 9);
    lv_obj_set_align(ui_IsenseCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IsenseCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_align(ui_IsenseCb, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_IsenseCb, lv_color_hex(0x0DF1F8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IsenseCb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_VprobeNCb = lv_checkbox_create(ui_Graph);
    lv_checkbox_set_text(ui_VprobeNCb, "VpN");
    lv_obj_set_width(ui_VprobeNCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VprobeNCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VprobeNCb, 130);
    lv_obj_set_y(ui_VprobeNCb, -33);
    lv_obj_set_align(ui_VprobeNCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VprobeNCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_VprobeNCb, lv_color_hex(0x0BF41E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VprobeNCb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GraphRetBtn = lv_btn_create(ui_Graph);
    lv_obj_set_width(ui_GraphRetBtn, 40);
    lv_obj_set_height(ui_GraphRetBtn, 22);
    lv_obj_set_x(ui_GraphRetBtn, 140);
    lv_obj_set_y(ui_GraphRetBtn, 74);
    lv_obj_set_align(ui_GraphRetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GraphRetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GraphRetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GraphRetBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GraphRetLbl = lv_label_create(ui_GraphRetBtn);
    lv_obj_set_width(ui_GraphRetLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GraphRetLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GraphRetLbl, -1);
    lv_obj_set_y(ui_GraphRetLbl, 0);
    lv_obj_set_align(ui_GraphRetLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GraphRetLbl, "RET");
    lv_obj_set_style_text_font(ui_GraphRetLbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GraphRetBtn, ui_event_GraphRetBtn, LV_EVENT_ALL, NULL);

}

void ui_Graph_screen_destroy(void)
{
    if(ui_Graph) lv_obj_del(ui_Graph);

    // NULL screen variables
    ui_Graph = NULL;
    ui_VoltChart = NULL;
    ui_VdiffCb = NULL;
    ui_VprobePCb = NULL;
    ui_VdriveCb = NULL;
    ui_IsenseCb = NULL;
    ui_VprobeNCb = NULL;
    ui_GraphRetBtn = NULL;
    ui_GraphRetLbl = NULL;

}
