// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_GRAPH_H
#define UI_GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Graph
extern void ui_Graph_screen_init(void);
extern void ui_Graph_screen_destroy(void);
extern lv_obj_t * ui_Graph;
extern lv_obj_t * ui_VoltChart;
extern lv_obj_t * ui_VdiffCb;
extern lv_obj_t * ui_VprobePCb;
extern lv_obj_t * ui_VdriveCb;
extern lv_obj_t * ui_IsenseCb;
extern lv_obj_t * ui_VprobeNCb;
extern void ui_event_GraphRetBtn(lv_event_t * e);
extern lv_obj_t * ui_GraphRetBtn;
extern lv_obj_t * ui_GraphRetLbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

