// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * uic_CalibrationsLbl;
lv_obj_t * uic_CurrentRT;
lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_MainPageTabs = NULL;
lv_obj_t * ui_VoltPage = NULL;
lv_obj_t * ui_PeakBtn = NULL;
lv_obj_t * ui_PeakLbl = NULL;
lv_obj_t * ui_HoldBtn = NULL;
lv_obj_t * ui_HldLbl = NULL;
lv_obj_t * ui_MinMeasVal = NULL;
lv_obj_t * ui_MinMeasLbl = NULL;
lv_obj_t * ui_MaxMeasLbl = NULL;
lv_obj_t * ui_MaxMeasVal = NULL;
lv_obj_t * ui_AverageMeasVal = NULL;
lv_obj_t * ui_VinDividerBox = NULL;
lv_obj_t * ui_VdiffMeasVal = NULL;
lv_obj_t * ui_VdispGraphSelBtn = NULL;
lv_obj_t * ui_AverageMeasLbl = NULL;
lv_obj_t * ui_RelBtn = NULL;
lv_obj_t * ui_RelLbl = NULL;
lv_obj_t * ui_MorevBtn = NULL;
lv_obj_t * ui_MorevLbl = NULL;
lv_obj_t * ui_VdiffSignLbl = NULL;
lv_obj_t * ui_VdiffRngLbl = NULL;
lv_obj_t * ui_VdiffBarVal = NULL;
lv_obj_t * ui_BarGraphScaleImg = NULL;
lv_obj_t * ui_VoltRangeLbl = NULL;
lv_obj_t * ui_VoltRangeDn = NULL;
lv_obj_t * ui_OhmPage = NULL;
lv_obj_t * ui_OhmMeasVal = NULL;
lv_obj_t * ui_OhmSelDn = NULL;
lv_obj_t * ui_OhmModeCb = NULL;
lv_obj_t * ui_OhmTrigBtn = NULL;
lv_obj_t * ui_OhmTrigLbl = NULL;
lv_obj_t * ui_OhmVLimitVal = NULL;
lv_obj_t * ui_OhmILimitVal = NULL;
lv_obj_t * ui_OhmBuzzBtn = NULL;
lv_obj_t * ui_DiodeModeLbl1 = NULL;
lv_obj_t * ui_DiodePage = NULL;
lv_obj_t * ui_DiodeVfSelDn = NULL;
lv_obj_t * ui_DiodeVfVal = NULL;
lv_obj_t * ui_DiodeModeLbl = NULL;
lv_obj_t * ui_VdiodeLimitVal = NULL;
lv_obj_t * ui_IdiodeLimitVal = NULL;
lv_obj_t * ui_DiodeTrigBtn = NULL;
lv_obj_t * ui_VdTrigLbl = NULL;
lv_obj_t * ui_DiodeMeasModeCb = NULL;
lv_obj_t * ui_DiodeBuzzBtn = NULL;
lv_obj_t * ui_SMUPage = NULL;
lv_obj_t * ui_VoltgeRT = NULL;
lv_obj_t * ui_SMUVoltLbl = NULL;
lv_obj_t * ui_VoltLimitSpin = NULL;
lv_obj_t * ui_VLIMLbl = NULL;
lv_obj_t * ui_CurrLimitSpin = NULL;
lv_obj_t * ui_ILIMLbl = NULL;
lv_obj_t * ui_CurrentRT = NULL;
lv_obj_t * ui_SMUmALbl = NULL;
lv_obj_t * ui_SMUOnOffBtn = NULL;
lv_obj_t * ui_SMUOnOffLbl = NULL;
lv_obj_t * ui_Options = NULL;
lv_obj_t * ui_FlipDispCntrl = NULL;
lv_obj_t * ui_StandbyOptDn = NULL;
lv_obj_t * ui_StandbyLbl = NULL;
lv_obj_t * ui_MaxBrightnessCtrl = NULL;
lv_obj_t * ui_MaxBrightnessLbl = NULL;
lv_obj_t * ui_MinBrightnessCtrl = NULL;
lv_obj_t * ui_MinBrightnessLbl = NULL;
lv_obj_t * ui_BacklightToutCtrl = NULL;
lv_obj_t * ui_BacklightToutLbl = NULL;
lv_obj_t * ui_MoreOptionsBtn = NULL;
lv_obj_t * ui_CalibrationsLbl = NULL;
lv_obj_t * ui_timeInfo = NULL;
lv_obj_t * ui_ESPNOW = NULL;
lv_obj_t * ui_WifiImg = NULL;
lv_obj_t * ui_SysInfoLbl = NULL;
lv_obj_t * ui_BattInf = NULL;
lv_obj_t * ui_BattLevLbl = NULL;
lv_obj_t * ui_ChargingImg = NULL;
// event funtions
void ui_event_MainPageTabs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ResetTimeouts(e);
    }
}

void ui_event_PeakBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PeakBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ResetTimeouts(e);
    }
}

void ui_event_HoldBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_HoldBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ResetTimeouts(e);
    }
}

void ui_event_VinDividerBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        SetVinDivider(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VdiffRngLbl, _UI_LABEL_PROPERTY_TEXT, "6.0V");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_VdiffRngLbl, _UI_LABEL_PROPERTY_TEXT, "60V");
    }
}

void ui_event_VdispGraphSelBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph_screen_init);
    }
}

void ui_event_RelBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_RelBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        ResetTimeouts(e);
    }
}

void ui_event_MorevBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_screen_change(&ui_Volt_More, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Volt_More_screen_init);
        ResetTimeouts(e);
    }
}

void ui_event_VoltRangeDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        SetViffRangeFn(e);
        ResetTimeouts(e);
    }
}

void ui_event_OhmSelDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetOhmRangeFn(e);
    }
}

void ui_event_OhmModeCb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_OhmTrigBtn, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_OhmTrigBtn, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OhmSampleModeFn(e);
    }
}

void ui_event_OhmBuzzBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_OhmBuzzBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        SetOhmBuzzFn(e);
    }
}

void ui_event_DiodeVfSelDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetDiodeTypeFn(e);
    }
}

void ui_event_DiodeMeasModeCb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_DiodeTrigBtn, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_DiodeTrigBtn, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        DiodeSampleModeFn(e);
    }
}

void ui_event_DiodeBuzzBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_DiodeBuzzBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        SetDiodeBuzzFn(e);
    }
}

void ui_event_VoltLimitSpin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SMU_V_SetFn(e);
    }
}

void ui_event_CurrLimitSpin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SMU_I_SetFn(e);
    }
}

void ui_event_SMUOnOffBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_SMUOnOffLbl, target, "ON", "OFF");
    }
}

void ui_event_FlipDispCntrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlipScreenFn(e);
    }
}

void ui_event_StandbyOptDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        StandbyModeFn(e);
    }
}

void ui_event_MaxBrightnessCtrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeMaxBrightness(e);
    }
}

void ui_event_MinBrightnessCtrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeMinBrightness(e);
    }
}

void ui_event_BacklightToutCtrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeBacklightTout(e);
    }
}

void ui_event_MoreOptionsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MoreOptions, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoreOptions_screen_init);
    }
}

void ui_event_BattInf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_label_set_property(ui_BattLevLbl, _UI_LABEL_PROPERTY_TEXT, "");
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Main, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_MainPageTabs = lv_tabview_create(ui_Main, LV_DIR_BOTTOM, 20);
    lv_obj_set_width(ui_MainPageTabs, 320);
    lv_obj_set_height(ui_MainPageTabs, 143);
    lv_obj_set_x(ui_MainPageTabs, 0);
    lv_obj_set_y(ui_MainPageTabs, 8);
    lv_obj_set_align(ui_MainPageTabs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPageTabs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainPageTabs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPageTabs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_MainPageTabs), lv_color_hex(0x7D7D7D),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_MainPageTabs), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_VoltPage = lv_tabview_add_tab(ui_MainPageTabs, "VOLT");
    lv_obj_clear_flag(ui_VoltPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VoltPage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_VoltPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PeakBtn = lv_btn_create(ui_VoltPage);
    lv_obj_set_width(ui_PeakBtn, 55);
    lv_obj_set_height(ui_PeakBtn, 28);
    lv_obj_set_x(ui_PeakBtn, 70);
    lv_obj_set_y(ui_PeakBtn, 44);
    lv_obj_set_align(ui_PeakBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PeakBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PeakBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PeakBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PeakBtn, lv_color_hex(0x474444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PeakBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PeakBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PeakBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PeakBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PeakBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PeakBtn, lv_color_hex(0xF90707), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PeakBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_PeakBtn, lv_color_hex(0xFC0303), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_PeakBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_PeakBtn, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_PeakBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_PeakLbl = lv_label_create(ui_PeakBtn);
    lv_obj_set_width(ui_PeakLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PeakLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PeakLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PeakLbl, " PK ");
    lv_obj_set_style_text_font(ui_PeakLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HoldBtn = lv_btn_create(ui_VoltPage);
    lv_obj_set_width(ui_HoldBtn, 55);
    lv_obj_set_height(ui_HoldBtn, 28);
    lv_obj_set_x(ui_HoldBtn, 11);
    lv_obj_set_y(ui_HoldBtn, 44);
    lv_obj_set_align(ui_HoldBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HoldBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HoldBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HoldBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HoldBtn, lv_color_hex(0x474444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HoldBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HoldBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HoldBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HoldBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HoldBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HoldBtn, lv_color_hex(0xDB0D26), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HoldBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_HoldBtn, lv_color_hex(0xFC0303), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_HoldBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_HoldBtn, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_HoldBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_HldLbl = lv_label_create(ui_HoldBtn);
    lv_obj_set_width(ui_HldLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HldLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HldLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HldLbl, "HLD");
    lv_obj_add_state(ui_HldLbl, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_HldLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinMeasVal = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_MinMeasVal, 18);
    lv_obj_set_width(ui_MinMeasVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MinMeasVal, 35);
    lv_obj_set_y(ui_MinMeasVal, 9);
    lv_obj_set_align(ui_MinMeasVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MinMeasVal, "0.00000V");
    lv_obj_set_style_text_color(ui_MinMeasVal, lv_color_hex(0xF80C1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinMeasVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinMeasVal, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinMeasLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_MinMeasLbl, 16);
    lv_obj_set_width(ui_MinMeasLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MinMeasLbl, -12);
    lv_obj_set_y(ui_MinMeasLbl, 6);
    lv_obj_set_align(ui_MinMeasLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MinMeasLbl, "Min:");
    lv_obj_set_style_text_color(ui_MinMeasLbl, lv_color_hex(0xF80C1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinMeasLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinMeasLbl, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxMeasLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_MaxMeasLbl, 18);
    lv_obj_set_width(ui_MaxMeasLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MaxMeasLbl, -12);
    lv_obj_set_y(ui_MaxMeasLbl, 28);
    lv_obj_set_align(ui_MaxMeasLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MaxMeasLbl, "Max:");
    lv_obj_set_style_text_color(ui_MaxMeasLbl, lv_color_hex(0x0AF820), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxMeasLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxMeasLbl, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxMeasVal = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_MaxMeasVal, 18);
    lv_obj_set_width(ui_MaxMeasVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MaxMeasVal, 35);
    lv_obj_set_y(ui_MaxMeasVal, 29);
    lv_obj_set_align(ui_MaxMeasVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MaxMeasVal, "0.00000V");
    lv_obj_set_style_text_color(ui_MaxMeasVal, lv_color_hex(0x0AF820), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxMeasVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxMeasVal, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AverageMeasVal = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_AverageMeasVal, 17);
    lv_obj_set_width(ui_AverageMeasVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AverageMeasVal, 35);
    lv_obj_set_y(ui_AverageMeasVal, 48);
    lv_obj_set_align(ui_AverageMeasVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AverageMeasVal, "0.00000V");
    lv_obj_set_style_text_color(ui_AverageMeasVal, lv_color_hex(0x0926F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AverageMeasVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AverageMeasVal, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VinDividerBox = lv_checkbox_create(ui_VoltPage);
    lv_checkbox_set_text(ui_VinDividerBox, "Vin/25");
    lv_obj_set_width(ui_VinDividerBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VinDividerBox, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_VinDividerBox, 82);
    lv_obj_set_y(ui_VinDividerBox, 49);
    lv_obj_set_align(ui_VinDividerBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VinDividerBox, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_VinDividerBox, lv_color_hex(0x1A9BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VinDividerBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VinDividerBox, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_VinDividerBox, lv_color_hex(0xF52546), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_VinDividerBox, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_pad_left(ui_VinDividerBox, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VinDividerBox, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VinDividerBox, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VinDividerBox, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VinDividerBox, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_VdiffMeasVal = lv_label_create(ui_VoltPage);
    lv_obj_set_width(ui_VdiffMeasVal, 261);
    lv_obj_set_height(ui_VdiffMeasVal, 45);
    lv_obj_set_x(ui_VdiffMeasVal, -10);
    lv_obj_set_y(ui_VdiffMeasVal, -40);
    lv_obj_set_align(ui_VdiffMeasVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_VdiffMeasVal, "+00.00000V");
    lv_obj_set_style_text_color(ui_VdiffMeasVal, lv_color_hex(0x12CAEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiffMeasVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdiffMeasVal, &ui_font_SegD48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VdiffMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VdiffMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VdiffMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VdiffMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdispGraphSelBtn = lv_btn_create(ui_VdiffMeasVal);
    lv_obj_set_width(ui_VdispGraphSelBtn, 259);
    lv_obj_set_height(ui_VdispGraphSelBtn, 43);
    lv_obj_set_x(ui_VdispGraphSelBtn, 3);
    lv_obj_set_y(ui_VdispGraphSelBtn, -1);
    lv_obj_set_align(ui_VdispGraphSelBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VdispGraphSelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VdispGraphSelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VdispGraphSelBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VdispGraphSelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VdispGraphSelBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VdispGraphSelBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VdispGraphSelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AverageMeasLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_height(ui_AverageMeasLbl, 20);
    lv_obj_set_width(ui_AverageMeasLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AverageMeasLbl, -9);
    lv_obj_set_y(ui_AverageMeasLbl, 48);
    lv_obj_set_align(ui_AverageMeasLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AverageMeasLbl, "Avg:");
    lv_obj_set_style_text_color(ui_AverageMeasLbl, lv_color_hex(0x0926F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AverageMeasLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AverageMeasLbl, &ui_font_SegD22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RelBtn = lv_btn_create(ui_VoltPage);
    lv_obj_set_width(ui_RelBtn, 54);
    lv_obj_set_height(ui_RelBtn, 28);
    lv_obj_set_x(ui_RelBtn, 129);
    lv_obj_set_y(ui_RelBtn, 44);
    lv_obj_set_align(ui_RelBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RelBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RelBtn, lv_color_hex(0x474444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RelBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RelBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RelBtn, lv_color_hex(0x1829EC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RelBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_RelBtn, lv_color_hex(0xFC0303), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_RelBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_RelBtn, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_RelBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_RelLbl = lv_label_create(ui_RelBtn);
    lv_obj_set_width(ui_RelLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RelLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RelLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RelLbl, "REL");
    lv_obj_add_state(ui_RelLbl, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_text_font(ui_RelLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MorevBtn = lv_btn_create(ui_VoltPage);
    lv_obj_set_width(ui_MorevBtn, 57);
    lv_obj_set_height(ui_MorevBtn, 32);
    lv_obj_set_x(ui_MorevBtn, 130);
    lv_obj_set_y(ui_MorevBtn, -41);
    lv_obj_set_align(ui_MorevBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MorevBtn, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_MorevBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MorevBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MorevBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MorevBtn, lv_color_hex(0x837F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MorevBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MorevBtn, lv_color_hex(0xB0B0EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MorevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MorevBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MorevBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MorevLbl = lv_label_create(ui_MorevBtn);
    lv_obj_set_width(ui_MorevLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MorevLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MorevLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MorevLbl, "More");
    lv_obj_set_style_text_color(ui_MorevLbl, lv_color_hex(0xE8FAE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MorevLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiffSignLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_width(ui_VdiffSignLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdiffSignLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiffSignLbl, -152);
    lv_obj_set_y(ui_VdiffSignLbl, -12);
    lv_obj_set_align(ui_VdiffSignLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VdiffSignLbl, "+");
    lv_obj_set_style_text_color(ui_VdiffSignLbl, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiffSignLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdiffSignLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiffRngLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_width(ui_VdiffRngLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdiffRngLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiffRngLbl, 143);
    lv_obj_set_y(ui_VdiffRngLbl, -13);
    lv_obj_set_align(ui_VdiffRngLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VdiffRngLbl, "24V");
    lv_obj_set_style_text_color(ui_VdiffRngLbl, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiffRngLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VdiffRngLbl, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdiffRngLbl, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiffBarVal = lv_bar_create(ui_VoltPage);
    lv_obj_set_width(ui_VdiffBarVal, 270);
    lv_obj_set_height(ui_VdiffBarVal, 14);
    lv_obj_set_x(ui_VdiffBarVal, -9);
    lv_obj_set_y(ui_VdiffBarVal, -13);
    lv_obj_set_align(ui_VdiffBarVal, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_VdiffBarVal, LV_STATE_USER_4);       /// States
    lv_obj_set_style_radius(ui_VdiffBarVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VdiffBarVal, lv_color_hex(0x3B3838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VdiffBarVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VdiffBarVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VdiffBarVal, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VdiffBarVal, lv_color_hex(0xBBC14A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VdiffBarVal, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VdiffBarVal, lv_color_hex(0xFEFEFE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VdiffBarVal, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarGraphScaleImg = lv_img_create(ui_VdiffBarVal);
    lv_img_set_src(ui_BarGraphScaleImg, &ui_img_bargraph_24fs_png);
    lv_obj_set_width(ui_BarGraphScaleImg, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_BarGraphScaleImg, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_BarGraphScaleImg, -1);
    lv_obj_set_y(ui_BarGraphScaleImg, -1);
    lv_obj_set_align(ui_BarGraphScaleImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarGraphScaleImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarGraphScaleImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltRangeLbl = lv_label_create(ui_VoltPage);
    lv_obj_set_width(ui_VoltRangeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltRangeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltRangeLbl, 14);
    lv_obj_set_y(ui_VoltRangeLbl, 12);
    lv_obj_set_align(ui_VoltRangeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltRangeLbl, "Range:");
    lv_obj_set_style_text_color(ui_VoltRangeLbl, lv_color_hex(0x1A9BF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltRangeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VoltRangeLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltRangeLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltRangeLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltRangeLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltRangeDn = lv_dropdown_create(ui_VoltPage);
    lv_dropdown_set_options(ui_VoltRangeDn, "Auto\nmV\n24V\n240V\n");
    lv_obj_set_width(ui_VoltRangeDn, 113);
    lv_obj_set_height(ui_VoltRangeDn, 30);
    lv_obj_set_x(ui_VoltRangeDn, 99);
    lv_obj_set_y(ui_VoltRangeDn, 12);
    lv_obj_set_align(ui_VoltRangeDn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_VoltRangeDn, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_VoltRangeDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_VoltRangeDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltRangeDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltRangeDn, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VoltRangeDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VoltRangeDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltRangeDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltRangeDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltRangeDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VoltRangeDn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltRangeDn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltRangeDn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltRangeDn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_VoltRangeDn, &lv_font_montserrat_18, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_OhmPage = lv_tabview_add_tab(ui_MainPageTabs, "OHM");
    lv_obj_clear_flag(ui_OhmPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OhmMeasVal = lv_label_create(ui_OhmPage);
    lv_obj_set_width(ui_OhmMeasVal, 314);
    lv_obj_set_height(ui_OhmMeasVal, 44);
    lv_obj_set_x(ui_OhmMeasVal, -11);
    lv_obj_set_y(ui_OhmMeasVal, -38);
    lv_obj_set_align(ui_OhmMeasVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OhmMeasVal, "999.99 MΩ");
    lv_obj_set_style_text_color(ui_OhmMeasVal, lv_color_hex(0x12CAEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmMeasVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmMeasVal, &ui_font_SegD48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OhmMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OhmMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OhmMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OhmMeasVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OhmSelDn = lv_dropdown_create(ui_OhmPage);
    lv_dropdown_set_options(ui_OhmSelDn, "Auto\n1 ohm\n1K\n10K\n100K\n1M\n10M\n1MHV\n10MHV");
    lv_obj_set_width(ui_OhmSelDn, 99);
    lv_obj_set_height(ui_OhmSelDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OhmSelDn, -57);
    lv_obj_set_y(ui_OhmSelDn, 0);
    lv_obj_set_align(ui_OhmSelDn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_OhmSelDn, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_OhmSelDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_OhmSelDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmSelDn, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_OhmSelDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmSelDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OhmSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OhmSelDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OhmSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OhmSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OhmSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OhmSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OhmSelDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OhmSelDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_OhmSelDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_OhmSelDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OhmModeCb = lv_checkbox_create(ui_OhmPage);
    lv_checkbox_set_text(ui_OhmModeCb, "Cont.");
    lv_obj_set_width(ui_OhmModeCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OhmModeCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OhmModeCb, 36);
    lv_obj_set_y(ui_OhmModeCb, -1);
    lv_obj_set_align(ui_OhmModeCb, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_OhmModeCb, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_OhmModeCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_OhmModeCb, lv_color_hex(0x1AFAF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmModeCb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmModeCb, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OhmTrigBtn = lv_btn_create(ui_OhmPage);
    lv_obj_set_width(ui_OhmTrigBtn, 87);
    lv_obj_set_height(ui_OhmTrigBtn, 44);
    lv_obj_set_x(ui_OhmTrigBtn, 39);
    lv_obj_set_y(ui_OhmTrigBtn, 38);
    lv_obj_set_align(ui_OhmTrigBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OhmTrigBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OhmTrigBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OhmTrigBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmTrigBtn, lv_color_hex(0x837F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OhmTrigBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_OhmTrigBtn, lv_color_hex(0xB0B0EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_OhmTrigBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_OhmTrigBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_OhmTrigBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmTrigBtn, lv_color_hex(0xF36262), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_OhmTrigBtn, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_OhmTrigLbl = lv_label_create(ui_OhmTrigBtn);
    lv_obj_set_width(ui_OhmTrigLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OhmTrigLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OhmTrigLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OhmTrigLbl, "Trig");
    lv_obj_set_style_text_color(ui_OhmTrigLbl, lv_color_hex(0xE2E9E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmTrigLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmTrigLbl, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_OhmTrigLbl, lv_color_hex(0x554F4F), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_OhmTrigLbl, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_OhmVLimitVal = lv_label_create(ui_OhmPage);
    lv_obj_set_width(ui_OhmVLimitVal, 150);
    lv_obj_set_height(ui_OhmVLimitVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OhmVLimitVal, -10);
    lv_obj_set_y(ui_OhmVLimitVal, 28);
    lv_obj_set_align(ui_OhmVLimitVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OhmVLimitVal, "VLIM = 2.0V");
    lv_obj_set_style_text_color(ui_OhmVLimitVal, lv_color_hex(0x0308C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmVLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmVLimitVal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmVLimitVal, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OhmVLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OhmVLimitVal, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OhmVLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OhmVLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OhmVLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OhmILimitVal = lv_label_create(ui_OhmPage);
    lv_obj_set_width(ui_OhmILimitVal, 150);
    lv_obj_set_height(ui_OhmILimitVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OhmILimitVal, -10);
    lv_obj_set_y(ui_OhmILimitVal, 50);
    lv_obj_set_align(ui_OhmILimitVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OhmILimitVal, "ILIM = 100uA");
    lv_obj_set_style_text_color(ui_OhmILimitVal, lv_color_hex(0xE0051E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OhmILimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OhmILimitVal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmILimitVal, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OhmILimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OhmILimitVal, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OhmILimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OhmILimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OhmILimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OhmBuzzBtn = lv_btn_create(ui_OhmPage);
    lv_obj_set_width(ui_OhmBuzzBtn, 71);
    lv_obj_set_height(ui_OhmBuzzBtn, 45);
    lv_obj_set_x(ui_OhmBuzzBtn, 121);
    lv_obj_set_y(ui_OhmBuzzBtn, 38);
    lv_obj_set_align(ui_OhmBuzzBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_OhmBuzzBtn, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_OhmBuzzBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OhmBuzzBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OhmBuzzBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmBuzzBtn, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OhmBuzzBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_OhmBuzzBtn, &ui_img_speakerofficon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OhmBuzzBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OhmBuzzBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OhmBuzzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OhmBuzzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OhmBuzzBtn, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_OhmBuzzBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_OhmBuzzBtn, &ui_img_speakeronicon_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_DiodeModeLbl1 = lv_label_create(ui_OhmPage);
    lv_obj_set_width(ui_DiodeModeLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DiodeModeLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DiodeModeLbl1, -134);
    lv_obj_set_y(ui_DiodeModeLbl1, 0);
    lv_obj_set_align(ui_DiodeModeLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DiodeModeLbl1, "Range:");
    lv_obj_set_style_text_color(ui_DiodeModeLbl1, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DiodeModeLbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiodePage = lv_tabview_add_tab(ui_MainPageTabs, "DIODE");
    lv_obj_add_state(ui_DiodePage, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_DiodePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DiodeVfSelDn = lv_dropdown_create(ui_DiodePage);
    lv_dropdown_set_options(ui_DiodeVfSelDn, "Low Vf\nZener\nLED");
    lv_obj_set_width(ui_DiodeVfSelDn, 106);
    lv_obj_set_height(ui_DiodeVfSelDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DiodeVfSelDn, -60);
    lv_obj_set_y(ui_DiodeVfSelDn, -1);
    lv_obj_set_align(ui_DiodeVfSelDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DiodeVfSelDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DiodeVfSelDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DiodeVfSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DiodeVfSelDn, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DiodeVfSelDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiodeVfSelDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DiodeVfSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DiodeVfSelDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DiodeVfSelDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DiodeVfSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DiodeVfSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DiodeVfSelDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DiodeVfSelDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DiodeVfSelDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_DiodeVfSelDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_DiodeVfSelDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiodeVfVal = lv_label_create(ui_DiodePage);
    lv_obj_set_width(ui_DiodeVfVal, 313);
    lv_obj_set_height(ui_DiodeVfVal, 44);
    lv_obj_set_x(ui_DiodeVfVal, -11);
    lv_obj_set_y(ui_DiodeVfVal, -40);
    lv_obj_set_align(ui_DiodeVfVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DiodeVfVal, "+00.000V");
    lv_obj_set_style_text_color(ui_DiodeVfVal, lv_color_hex(0x12CAEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DiodeVfVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DiodeVfVal, &ui_font_SegD48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DiodeVfVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DiodeVfVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DiodeVfVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DiodeVfVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiodeModeLbl = lv_label_create(ui_DiodePage);
    lv_obj_set_width(ui_DiodeModeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DiodeModeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DiodeModeLbl, -137);
    lv_obj_set_y(ui_DiodeModeLbl, -1);
    lv_obj_set_align(ui_DiodeModeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DiodeModeLbl, "Mode:");
    lv_obj_set_style_text_color(ui_DiodeModeLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DiodeModeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiodeLimitVal = lv_label_create(ui_DiodePage);
    lv_obj_set_width(ui_VdiodeLimitVal, 151);
    lv_obj_set_height(ui_VdiodeLimitVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiodeLimitVal, -11);
    lv_obj_set_y(ui_VdiodeLimitVal, 28);
    lv_obj_set_align(ui_VdiodeLimitVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_VdiodeLimitVal, "VLIM = 2.0V");
    lv_obj_set_style_text_color(ui_VdiodeLimitVal, lv_color_hex(0x0308C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiodeLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdiodeLimitVal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VdiodeLimitVal, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VdiodeLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VdiodeLimitVal, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IdiodeLimitVal = lv_label_create(ui_DiodePage);
    lv_obj_set_width(ui_IdiodeLimitVal, 151);
    lv_obj_set_height(ui_IdiodeLimitVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IdiodeLimitVal, -11);
    lv_obj_set_y(ui_IdiodeLimitVal, 50);
    lv_obj_set_align(ui_IdiodeLimitVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IdiodeLimitVal, "ILIM = 100uA");
    lv_obj_set_style_text_color(ui_IdiodeLimitVal, lv_color_hex(0xE0051E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IdiodeLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IdiodeLimitVal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IdiodeLimitVal, lv_color_hex(0x4D4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IdiodeLimitVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IdiodeLimitVal, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IdiodeLimitVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiodeTrigBtn = lv_btn_create(ui_DiodePage);
    lv_obj_set_width(ui_DiodeTrigBtn, 87);
    lv_obj_set_height(ui_DiodeTrigBtn, 44);
    lv_obj_set_x(ui_DiodeTrigBtn, 39);
    lv_obj_set_y(ui_DiodeTrigBtn, 38);
    lv_obj_set_align(ui_DiodeTrigBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_DiodeTrigBtn, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_DiodeTrigBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DiodeTrigBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DiodeTrigBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiodeTrigBtn, lv_color_hex(0x837F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DiodeTrigBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DiodeTrigBtn, lv_color_hex(0xB0B0EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DiodeTrigBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DiodeTrigBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DiodeTrigBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiodeTrigBtn, lv_color_hex(0xF36262), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_DiodeTrigBtn, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_VdTrigLbl = lv_label_create(ui_DiodeTrigBtn);
    lv_obj_set_width(ui_VdTrigLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdTrigLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VdTrigLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VdTrigLbl, "Trig");
    lv_obj_set_style_text_color(ui_VdTrigLbl, lv_color_hex(0xE2E9E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdTrigLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdTrigLbl, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_VdTrigLbl, lv_color_hex(0x554F4F), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_VdTrigLbl, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_DiodeMeasModeCb = lv_checkbox_create(ui_DiodePage);
    lv_checkbox_set_text(ui_DiodeMeasModeCb, "Cont.");
    lv_obj_set_width(ui_DiodeMeasModeCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DiodeMeasModeCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DiodeMeasModeCb, 36);
    lv_obj_set_y(ui_DiodeMeasModeCb, -2);
    lv_obj_set_align(ui_DiodeMeasModeCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DiodeMeasModeCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DiodeMeasModeCb, lv_color_hex(0x1AFAF4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DiodeMeasModeCb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DiodeMeasModeCb, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiodeBuzzBtn = lv_btn_create(ui_DiodePage);
    lv_obj_set_width(ui_DiodeBuzzBtn, 71);
    lv_obj_set_height(ui_DiodeBuzzBtn, 45);
    lv_obj_set_x(ui_DiodeBuzzBtn, 121);
    lv_obj_set_y(ui_DiodeBuzzBtn, 38);
    lv_obj_set_align(ui_DiodeBuzzBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DiodeBuzzBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DiodeBuzzBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DiodeBuzzBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiodeBuzzBtn, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DiodeBuzzBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DiodeBuzzBtn, &ui_img_speakerofficon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DiodeBuzzBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DiodeBuzzBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DiodeBuzzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DiodeBuzzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DiodeBuzzBtn, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DiodeBuzzBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_DiodeBuzzBtn, &ui_img_speakeronicon_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SMUPage = lv_tabview_add_tab(ui_MainPageTabs, "SMU");
    lv_obj_clear_flag(ui_SMUPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SMUPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SMUPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SMUPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SMUPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltgeRT = lv_textarea_create(ui_SMUPage);
    lv_obj_set_width(ui_VoltgeRT, 162);
    lv_obj_set_height(ui_VoltgeRT, 40);
    lv_obj_set_x(ui_VoltgeRT, -75);
    lv_obj_set_y(ui_VoltgeRT, -39);
    lv_obj_set_align(ui_VoltgeRT, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_VoltgeRT, "+12.598");
    lv_textarea_set_placeholder_text(ui_VoltgeRT, "Placeholder...");
    lv_obj_clear_flag(ui_VoltgeRT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_VoltgeRT, lv_color_hex(0x07F0F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltgeRT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltgeRT, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VoltgeRT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltgeRT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltgeRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SMUVoltLbl = lv_label_create(ui_VoltgeRT);
    lv_obj_set_width(ui_SMUVoltLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SMUVoltLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SMUVoltLbl, 56);
    lv_obj_set_y(ui_SMUVoltLbl, 1);
    lv_obj_set_align(ui_SMUVoltLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SMUVoltLbl, "V");
    lv_obj_set_style_text_font(ui_SMUVoltLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltLimitSpin = lv_spinbox_create(ui_SMUPage);
    lv_obj_set_width(ui_VoltLimitSpin, 154);
    lv_obj_set_height(ui_VoltLimitSpin, 60);
    lv_obj_set_x(ui_VoltLimitSpin, 77);
    lv_obj_set_y(ui_VoltLimitSpin, -31);
    lv_obj_set_align(ui_VoltLimitSpin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VoltLimitSpin, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_spinbox_set_digit_format(ui_VoltLimitSpin, 5, 2);
    lv_spinbox_set_range(ui_VoltLimitSpin, -15000, 15000);
    lv_spinbox_set_cursor_pos(ui_VoltLimitSpin, 1 - 1);
    lv_obj_set_style_bg_color(ui_VoltLimitSpin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoltLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VoltLimitSpin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VoltLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VoltLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltLimitSpin, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_VoltLimitSpin, lv_color_hex(0x2338F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltLimitSpin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VoltLimitSpin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltLimitSpin, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VLIMLbl = lv_label_create(ui_VoltLimitSpin);
    lv_obj_set_width(ui_VLIMLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VLIMLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VLIMLbl, -1);
    lv_obj_set_y(ui_VLIMLbl, -29);
    lv_obj_set_align(ui_VLIMLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VLIMLbl, "VLIM (V)");
    lv_obj_set_style_text_color(ui_VLIMLbl, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VLIMLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VLIMLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrLimitSpin = lv_spinbox_create(ui_SMUPage);
    lv_obj_set_width(ui_CurrLimitSpin, 155);
    lv_obj_set_height(ui_CurrLimitSpin, 60);
    lv_obj_set_x(ui_CurrLimitSpin, 77);
    lv_obj_set_y(ui_CurrLimitSpin, 30);
    lv_obj_set_align(ui_CurrLimitSpin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CurrLimitSpin, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_spinbox_set_digit_format(ui_CurrLimitSpin, 5, 2);
    lv_spinbox_set_range(ui_CurrLimitSpin, -99999, 99999);
    lv_spinbox_set_cursor_pos(ui_CurrLimitSpin, 1 - 1);
    lv_obj_set_style_bg_color(ui_CurrLimitSpin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrLimitSpin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrLimitSpin, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrLimitSpin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CurrLimitSpin, lv_color_hex(0xF90726), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrLimitSpin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CurrLimitSpin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrLimitSpin, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_CurrLimitSpin, LV_TEXT_ALIGN_LEFT, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ILIMLbl = lv_label_create(ui_CurrLimitSpin);
    lv_obj_set_width(ui_ILIMLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ILIMLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ILIMLbl, 1);
    lv_obj_set_y(ui_ILIMLbl, -30);
    lv_obj_set_align(ui_ILIMLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ILIMLbl, "ILIM (mA)");
    lv_obj_set_style_text_color(ui_ILIMLbl, lv_color_hex(0xFDFDFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ILIMLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ILIMLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentRT = lv_textarea_create(ui_SMUPage);
    lv_obj_set_width(ui_CurrentRT, 169);
    lv_obj_set_height(ui_CurrentRT, 42);
    lv_obj_set_x(ui_CurrentRT, -73);
    lv_obj_set_y(ui_CurrentRT, 0);
    lv_obj_set_align(ui_CurrentRT, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_CurrentRT, "+000.00");
    lv_textarea_set_placeholder_text(ui_CurrentRT, "Placeholder...");
    lv_obj_clear_flag(ui_CurrentRT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_CurrentRT, lv_color_hex(0xC3041F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentRT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentRT, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentRT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurrentRT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentRT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SMUmALbl = lv_label_create(ui_CurrentRT);
    lv_obj_set_width(ui_SMUmALbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SMUmALbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SMUmALbl, 63);
    lv_obj_set_y(ui_SMUmALbl, 0);
    lv_obj_set_align(ui_SMUmALbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SMUmALbl, "mA");
    lv_obj_set_style_text_color(ui_SMUmALbl, lv_color_hex(0xD80606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SMUmALbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SMUmALbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SMUOnOffBtn = lv_switch_create(ui_SMUPage);
    lv_obj_set_width(ui_SMUOnOffBtn, 79);
    lv_obj_set_height(ui_SMUOnOffBtn, 39);
    lv_obj_set_x(ui_SMUOnOffBtn, -114);
    lv_obj_set_y(ui_SMUOnOffBtn, 34);
    lv_obj_set_align(ui_SMUOnOffBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_SMUOnOffBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SMUOnOffBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SMUOnOffBtn, lv_color_hex(0x02370A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SMUOnOffBtn, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SMUOnOffBtn, lv_color_hex(0x09B411), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SMUOnOffBtn, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SMUOnOffBtn, lv_color_hex(0x030202), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SMUOnOffBtn, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SMUOnOffBtn, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SMUOnOffBtn, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SMUOnOffBtn, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SMUOnOffBtn, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SMUOnOffLbl = lv_label_create(ui_SMUPage);
    lv_obj_set_width(ui_SMUOnOffLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SMUOnOffLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SMUOnOffLbl, -47);
    lv_obj_set_y(ui_SMUOnOffLbl, 35);
    lv_obj_set_align(ui_SMUOnOffLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SMUOnOffLbl, "OFF");
    lv_obj_set_style_text_color(ui_SMUOnOffLbl, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SMUOnOffLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SMUOnOffLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Options = lv_tabview_add_tab(ui_MainPageTabs, "OPT.");
    lv_obj_clear_flag(ui_Options, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlipDispCntrl = lv_checkbox_create(ui_Options);
    lv_checkbox_set_text(ui_FlipDispCntrl, "Flip Screen");
    lv_obj_set_width(ui_FlipDispCntrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlipDispCntrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlipDispCntrl, -99);
    lv_obj_set_y(ui_FlipDispCntrl, 2);
    lv_obj_set_align(ui_FlipDispCntrl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FlipDispCntrl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_FlipDispCntrl, lv_color_hex(0x16E1F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FlipDispCntrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StandbyOptDn = lv_dropdown_create(ui_Options);
    lv_dropdown_set_options(ui_StandbyOptDn, "Always ON\n1 min\n2 min\n5 min\n10 min\n20 min\n30 min\n45 min\n1 hr");
    lv_obj_set_width(ui_StandbyOptDn, 110);
    lv_obj_set_height(ui_StandbyOptDn, 30);
    lv_obj_set_x(ui_StandbyOptDn, -99);
    lv_obj_set_y(ui_StandbyOptDn, -31);
    lv_obj_set_align(ui_StandbyOptDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyOptDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_StandbyOptDn, lv_color_hex(0x27C5F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StandbyOptDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StandbyOptDn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StandbyOptDn, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StandbyOptDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StandbyOptDn, lv_color_hex(0x078198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StandbyOptDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StandbyOptDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StandbyOptDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StandbyOptDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StandbyOptDn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StandbyOptDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_StandbyOptDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_StandbyOptDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_StandbyOptDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_StandbyOptDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StandbyLbl = lv_label_create(ui_Options);
    lv_obj_set_width(ui_StandbyLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StandbyLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StandbyLbl, -120);
    lv_obj_set_y(ui_StandbyLbl, -54);
    lv_obj_set_align(ui_StandbyLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyLbl, "STANDBY");
    lv_obj_set_style_text_color(ui_StandbyLbl, lv_color_hex(0x1650F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StandbyLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxBrightnessCtrl = lv_slider_create(ui_Options);
    lv_slider_set_range(ui_MaxBrightnessCtrl, 3, 100);
    lv_slider_set_value(ui_MaxBrightnessCtrl, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MaxBrightnessCtrl) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MaxBrightnessCtrl, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_MaxBrightnessCtrl, 150);
    lv_obj_set_height(ui_MaxBrightnessCtrl, 25);
    lv_obj_set_x(ui_MaxBrightnessCtrl, 45);
    lv_obj_set_y(ui_MaxBrightnessCtrl, -46);
    lv_obj_set_align(ui_MaxBrightnessCtrl, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MaxBrightnessCtrl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MaxBrightnessCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MaxBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MaxBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MaxBrightnessCtrl, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MaxBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_MaxBrightnessCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MaxBrightnessCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MaxBrightnessCtrl, -17, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MaxBrightnessCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MaxBrightnessLbl = lv_label_create(ui_MaxBrightnessCtrl);
    lv_obj_set_width(ui_MaxBrightnessLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxBrightnessLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxBrightnessLbl, 1);
    lv_obj_set_y(ui_MaxBrightnessLbl, -15);
    lv_obj_set_align(ui_MaxBrightnessLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MaxBrightnessLbl, "Brightness: [70%]");
    lv_obj_set_style_text_color(ui_MaxBrightnessLbl, lv_color_hex(0x27C5F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxBrightnessLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxBrightnessLbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinBrightnessCtrl = lv_slider_create(ui_Options);
    lv_slider_set_range(ui_MinBrightnessCtrl, 4, 30);
    lv_slider_set_value(ui_MinBrightnessCtrl, 8, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MinBrightnessCtrl) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MinBrightnessCtrl, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_MinBrightnessCtrl, 150);
    lv_obj_set_height(ui_MinBrightnessCtrl, 25);
    lv_obj_set_x(ui_MinBrightnessCtrl, 45);
    lv_obj_set_y(ui_MinBrightnessCtrl, -4);
    lv_obj_set_align(ui_MinBrightnessCtrl, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MinBrightnessCtrl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinBrightnessCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MinBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MinBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MinBrightnessCtrl, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MinBrightnessCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_MinBrightnessCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MinBrightnessCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MinBrightnessCtrl, -17, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MinBrightnessCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MinBrightnessLbl = lv_label_create(ui_MinBrightnessCtrl);
    lv_obj_set_width(ui_MinBrightnessLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinBrightnessLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinBrightnessLbl, 1);
    lv_obj_set_y(ui_MinBrightnessLbl, -15);
    lv_obj_set_align(ui_MinBrightnessLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MinBrightnessLbl, "LP Brightness: [8%]");
    lv_obj_set_style_text_color(ui_MinBrightnessLbl, lv_color_hex(0x27C5F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinBrightnessLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinBrightnessLbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacklightToutCtrl = lv_slider_create(ui_Options);
    lv_slider_set_range(ui_BacklightToutCtrl, 0, 60);
    lv_slider_set_value(ui_BacklightToutCtrl, 6, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BacklightToutCtrl) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BacklightToutCtrl, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_BacklightToutCtrl, 150);
    lv_obj_set_height(ui_BacklightToutCtrl, 25);
    lv_obj_set_x(ui_BacklightToutCtrl, 45);
    lv_obj_set_y(ui_BacklightToutCtrl, 37);
    lv_obj_set_align(ui_BacklightToutCtrl, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BacklightToutCtrl, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BacklightToutCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BacklightToutCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BacklightToutCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BacklightToutCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BacklightToutCtrl, 19, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BacklightToutCtrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_BacklightToutCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BacklightToutCtrl, -7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BacklightToutCtrl, -17, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BacklightToutCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BacklightToutLbl = lv_label_create(ui_BacklightToutCtrl);
    lv_obj_set_width(ui_BacklightToutLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BacklightToutLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BacklightToutLbl, 1);
    lv_obj_set_y(ui_BacklightToutLbl, -15);
    lv_obj_set_align(ui_BacklightToutLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BacklightToutLbl, "BL Timeout: [30 sec]");
    lv_obj_set_style_text_color(ui_BacklightToutLbl, lv_color_hex(0x27C5F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BacklightToutLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BacklightToutLbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoreOptionsBtn = lv_btn_create(ui_Options);
    lv_obj_set_width(ui_MoreOptionsBtn, 110);
    lv_obj_set_height(ui_MoreOptionsBtn, 37);
    lv_obj_set_x(ui_MoreOptionsBtn, -99);
    lv_obj_set_y(ui_MoreOptionsBtn, 37);
    lv_obj_set_align(ui_MoreOptionsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoreOptionsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoreOptionsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationsLbl = lv_label_create(ui_MoreOptionsBtn);
    lv_obj_set_width(ui_CalibrationsLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationsLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationsLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationsLbl, "More Options");
    lv_obj_set_style_text_align(ui_CalibrationsLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeInfo = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_timeInfo, 86);
    lv_obj_set_height(ui_timeInfo, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_timeInfo, 3);
    lv_obj_set_y(ui_timeInfo, 0);
    lv_textarea_set_text(ui_timeInfo, "10:34:27");
    lv_textarea_set_placeholder_text(ui_timeInfo, "Placeholder...");
    lv_textarea_set_one_line(ui_timeInfo, true);
    lv_obj_set_style_text_color(ui_timeInfo, lv_color_hex(0xF6F306), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeInfo, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timeInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_timeInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_timeInfo, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeInfo, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ESPNOW = lv_img_create(ui_Main);
    lv_img_set_src(ui_ESPNOW, &ui_img_icn_pc_png);
    lv_obj_set_width(ui_ESPNOW, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ESPNOW, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_ESPNOW, 112);
    lv_obj_set_y(ui_ESPNOW, -73);
    lv_obj_set_align(ui_ESPNOW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ESPNOW, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ESPNOW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_ESPNOW, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_ESPNOW, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ESPNOW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiImg = lv_img_create(ui_Main);
    lv_img_set_src(ui_WifiImg, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_WifiImg, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_WifiImg, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_WifiImg, 144);
    lv_obj_set_y(ui_WifiImg, -73);
    lv_obj_set_align(ui_WifiImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_WifiImg, lv_color_hex(0x484847), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_WifiImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SysInfoLbl = lv_label_create(ui_Main);
    lv_obj_set_width(ui_SysInfoLbl, 120);
    lv_obj_set_height(ui_SysInfoLbl, 17);
    lv_obj_set_x(ui_SysInfoLbl, -21);
    lv_obj_set_y(ui_SysInfoLbl, -76);
    lv_obj_set_align(ui_SysInfoLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SysInfoLbl, "Sys Info");
    lv_obj_set_style_text_color(ui_SysInfoLbl, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SysInfoLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SysInfoLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SysInfoLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattInf = lv_bar_create(ui_Main);
    lv_bar_set_value(ui_BattInf, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BattInf, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BattInf, 35);
    lv_obj_set_height(ui_BattInf, 16);
    lv_obj_set_x(ui_BattInf, 60);
    lv_obj_set_y(ui_BattInf, -74);
    lv_obj_set_align(ui_BattInf, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BattInf, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BattInf, lv_color_hex(0x061CF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BattInf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BattInf, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BattLevLbl = lv_label_create(ui_BattInf);
    lv_obj_set_width(ui_BattLevLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattLevLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BattLevLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BattLevLbl, "50%");
    lv_obj_set_style_text_color(ui_BattLevLbl, lv_color_hex(0xE3FD04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattLevLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BattLevLbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargingImg = lv_img_create(ui_Main);
    lv_img_set_src(ui_ChargingImg, &ui_img_chargein_png);
    lv_obj_set_width(ui_ChargingImg, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_ChargingImg, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_ChargingImg, 85);
    lv_obj_set_y(ui_ChargingImg, -74);
    lv_obj_set_align(ui_ChargingImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargingImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ChargingImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ChargingImg, lv_color_hex(0x1E1E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ChargingImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PeakBtn, ui_event_PeakBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HoldBtn, ui_event_HoldBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VinDividerBox, ui_event_VinDividerBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VdispGraphSelBtn, ui_event_VdispGraphSelBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RelBtn, ui_event_RelBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MorevBtn, ui_event_MorevBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VoltRangeDn, ui_event_VoltRangeDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OhmSelDn, ui_event_OhmSelDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OhmModeCb, ui_event_OhmModeCb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OhmBuzzBtn, ui_event_OhmBuzzBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DiodeVfSelDn, ui_event_DiodeVfSelDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DiodeMeasModeCb, ui_event_DiodeMeasModeCb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DiodeBuzzBtn, ui_event_DiodeBuzzBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VoltLimitSpin, ui_event_VoltLimitSpin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurrLimitSpin, ui_event_CurrLimitSpin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SMUOnOffBtn, ui_event_SMUOnOffBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FlipDispCntrl, ui_event_FlipDispCntrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StandbyOptDn, ui_event_StandbyOptDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MaxBrightnessCtrl, ui_event_MaxBrightnessCtrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MinBrightnessCtrl, ui_event_MinBrightnessCtrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BacklightToutCtrl, ui_event_BacklightToutCtrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoreOptionsBtn, ui_event_MoreOptionsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainPageTabs, ui_event_MainPageTabs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BattInf, ui_event_BattInf, LV_EVENT_ALL, NULL);
    uic_CurrentRT = ui_CurrentRT;
    uic_CalibrationsLbl = ui_CalibrationsLbl;

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_MainPageTabs = NULL;
    ui_VoltPage = NULL;
    ui_PeakBtn = NULL;
    ui_PeakLbl = NULL;
    ui_HoldBtn = NULL;
    ui_HldLbl = NULL;
    ui_MinMeasVal = NULL;
    ui_MinMeasLbl = NULL;
    ui_MaxMeasLbl = NULL;
    ui_MaxMeasVal = NULL;
    ui_AverageMeasVal = NULL;
    ui_VinDividerBox = NULL;
    ui_VdiffMeasVal = NULL;
    ui_VdispGraphSelBtn = NULL;
    ui_AverageMeasLbl = NULL;
    ui_RelBtn = NULL;
    ui_RelLbl = NULL;
    ui_MorevBtn = NULL;
    ui_MorevLbl = NULL;
    ui_VdiffSignLbl = NULL;
    ui_VdiffRngLbl = NULL;
    ui_VdiffBarVal = NULL;
    ui_BarGraphScaleImg = NULL;
    ui_VoltRangeLbl = NULL;
    ui_VoltRangeDn = NULL;
    ui_OhmPage = NULL;
    ui_OhmMeasVal = NULL;
    ui_OhmSelDn = NULL;
    ui_OhmModeCb = NULL;
    ui_OhmTrigBtn = NULL;
    ui_OhmTrigLbl = NULL;
    ui_OhmVLimitVal = NULL;
    ui_OhmILimitVal = NULL;
    ui_OhmBuzzBtn = NULL;
    ui_DiodeModeLbl1 = NULL;
    ui_DiodePage = NULL;
    ui_DiodeVfSelDn = NULL;
    ui_DiodeVfVal = NULL;
    ui_DiodeModeLbl = NULL;
    ui_VdiodeLimitVal = NULL;
    ui_IdiodeLimitVal = NULL;
    ui_DiodeTrigBtn = NULL;
    ui_VdTrigLbl = NULL;
    ui_DiodeMeasModeCb = NULL;
    ui_DiodeBuzzBtn = NULL;
    ui_SMUPage = NULL;
    ui_VoltgeRT = NULL;
    ui_SMUVoltLbl = NULL;
    ui_VoltLimitSpin = NULL;
    ui_VLIMLbl = NULL;
    ui_CurrLimitSpin = NULL;
    ui_ILIMLbl = NULL;
    uic_CurrentRT = NULL;
    ui_CurrentRT = NULL;
    ui_SMUmALbl = NULL;
    ui_SMUOnOffBtn = NULL;
    ui_SMUOnOffLbl = NULL;
    ui_Options = NULL;
    ui_FlipDispCntrl = NULL;
    ui_StandbyOptDn = NULL;
    ui_StandbyLbl = NULL;
    ui_MaxBrightnessCtrl = NULL;
    ui_MaxBrightnessLbl = NULL;
    ui_MinBrightnessCtrl = NULL;
    ui_MinBrightnessLbl = NULL;
    ui_BacklightToutCtrl = NULL;
    ui_BacklightToutLbl = NULL;
    ui_MoreOptionsBtn = NULL;
    uic_CalibrationsLbl = NULL;
    ui_CalibrationsLbl = NULL;
    ui_timeInfo = NULL;
    ui_ESPNOW = NULL;
    ui_WifiImg = NULL;
    ui_SysInfoLbl = NULL;
    ui_BattInf = NULL;
    ui_BattLevLbl = NULL;
    ui_ChargingImg = NULL;

}
