// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_MOREOPTIONS_H
#define UI_MOREOPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MoreOptions
extern void ui_MoreOptions_screen_init(void);
extern void ui_MoreOptions_screen_destroy(void);
extern lv_obj_t * ui_MoreOptions;
extern lv_obj_t * ui_CalListLbl;
extern lv_obj_t * ui_CalListDn;
extern void ui_event_MoreOptionsRetBtn(lv_event_t * e);
extern lv_obj_t * ui_MoreOptionsRetBtn;
extern void ui_event_MoreOptionsRetLbl(lv_event_t * e);
extern lv_obj_t * ui_MoreOptionsRetLbl;
extern lv_obj_t * ui_TimeZoneLbl;
extern void ui_event_TimeZonesDn(lv_event_t * e);
extern lv_obj_t * ui_TimeZonesDn;
extern void ui_event_DaylightCorrCb(lv_event_t * e);
extern lv_obj_t * ui_DaylightCorrCb;
extern void ui_event_WirelessSetupBtn(lv_event_t * e);
extern lv_obj_t * ui_WirelessSetupBtn;
extern lv_obj_t * ui_MoreOptionsLbl;
extern void ui_event_MaxSleepTimeCtrl(lv_event_t * e);
extern lv_obj_t * ui_MaxSleepTimeCtrl;
extern lv_obj_t * ui_MaxSleepTimeLbl;
extern void ui_event_KeepOnWithChargerCb(lv_event_t * e);
extern lv_obj_t * ui_KeepOnWithChargerCb;
extern void ui_event_ExecCalBtn(lv_event_t * e);
extern lv_obj_t * ui_ExecCalBtn;
extern void ui_event_ExecCalLbl(lv_event_t * e);
extern lv_obj_t * ui_ExecCalLbl;
extern void ui_event_BatteryProtectionCb(lv_event_t * e);
extern lv_obj_t * ui_BatteryProtectionCb;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

