// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * ui_Messages = NULL;
lv_obj_t * ui_MessagesScr = NULL;
lv_obj_t * ui_MsgNoBtn = NULL;
lv_obj_t * ui_MsgNoLbl = NULL;
lv_obj_t * ui_MsgYesBtn = NULL;
lv_obj_t * ui_MsgYesLbl = NULL;
// event funtions
void ui_event_MsgNoBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_MsgYesBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Messages_screen_init(void)
{
    ui_Messages = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Messages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Messages, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Messages, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessagesScr = lv_textarea_create(ui_Messages);
    lv_obj_set_width(ui_MessagesScr, 313);
    lv_obj_set_height(ui_MessagesScr, 156);
    lv_obj_set_x(ui_MessagesScr, 0);
    lv_obj_set_y(ui_MessagesScr, -1);
    lv_obj_set_align(ui_MessagesScr, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MessagesScr, "System messages displayed here.");
    lv_textarea_set_placeholder_text(ui_MessagesScr, "Placeholder...");
    lv_obj_set_style_text_color(ui_MessagesScr, lv_color_hex(0x34F306), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MessagesScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MessagesScr, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MessagesScr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MessagesScr, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MessagesScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MessagesScr, lv_color_hex(0x23E405), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MessagesScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MessagesScr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MessagesScr, lv_color_hex(0x34F306), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MessagesScr, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_MsgNoBtn = lv_btn_create(ui_Messages);
    lv_obj_set_width(ui_MsgNoBtn, 60);
    lv_obj_set_height(ui_MsgNoBtn, 33);
    lv_obj_set_x(ui_MsgNoBtn, 124);
    lv_obj_set_y(ui_MsgNoBtn, 56);
    lv_obj_set_align(ui_MsgNoBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MsgNoBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MsgNoBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MsgNoLbl = lv_label_create(ui_MsgNoBtn);
    lv_obj_set_width(ui_MsgNoLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MsgNoLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MsgNoLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgNoLbl, "No");
    lv_obj_set_style_text_font(ui_MsgNoLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MsgYesBtn = lv_btn_create(ui_Messages);
    lv_obj_set_width(ui_MsgYesBtn, 60);
    lv_obj_set_height(ui_MsgYesBtn, 33);
    lv_obj_set_x(ui_MsgYesBtn, 60);
    lv_obj_set_y(ui_MsgYesBtn, 56);
    lv_obj_set_align(ui_MsgYesBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MsgYesBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MsgYesBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MsgYesLbl = lv_label_create(ui_MsgYesBtn);
    lv_obj_set_width(ui_MsgYesLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MsgYesLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MsgYesLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgYesLbl, "Yes");
    lv_obj_set_style_text_font(ui_MsgYesLbl, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MsgNoBtn, ui_event_MsgNoBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MsgYesBtn, ui_event_MsgYesBtn, LV_EVENT_ALL, NULL);

}

void ui_Messages_screen_destroy(void)
{
    if(ui_Messages) lv_obj_del(ui_Messages);

    // NULL screen variables
    ui_Messages = NULL;
    ui_MessagesScr = NULL;
    ui_MsgNoBtn = NULL;
    ui_MsgNoLbl = NULL;
    ui_MsgYesBtn = NULL;
    ui_MsgYesLbl = NULL;

}
