// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_MESSAGES_H
#define UI_MESSAGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Messages
extern void ui_Messages_screen_init(void);
extern void ui_Messages_screen_destroy(void);
extern lv_obj_t * ui_Messages;
extern lv_obj_t * ui_MessagesScr;
extern void ui_event_MsgNoBtn(lv_event_t * e);
extern lv_obj_t * ui_MsgNoBtn;
extern lv_obj_t * ui_MsgNoLbl;
extern void ui_event_MsgYesBtn(lv_event_t * e);
extern lv_obj_t * ui_MsgYesBtn;
extern lv_obj_t * ui_MsgYesLbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

