// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * ui_MoreOptions = NULL;
lv_obj_t * ui_CalListLbl = NULL;
lv_obj_t * ui_CalListDn = NULL;
lv_obj_t * ui_MoreOptionsRetBtn = NULL;
lv_obj_t * ui_MoreOptionsRetLbl = NULL;
lv_obj_t * ui_TimeZoneLbl = NULL;
lv_obj_t * ui_TimeZonesDn = NULL;
lv_obj_t * ui_DaylightCorrCb = NULL;
lv_obj_t * ui_WirelessSetupBtn = NULL;
lv_obj_t * ui_MoreOptionsLbl = NULL;
lv_obj_t * ui_MaxSleepTimeCtrl = NULL;
lv_obj_t * ui_MaxSleepTimeLbl = NULL;
lv_obj_t * ui_KeepOnWithChargerCb = NULL;
lv_obj_t * ui_ExecCalBtn = NULL;
lv_obj_t * ui_ExecCalLbl = NULL;
lv_obj_t * ui_BatteryProtectionCb = NULL;
// event funtions
void ui_event_MoreOptionsRetBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_MoreOptionsRetLbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFi, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFi_screen_init);
    }
}

void ui_event_TimeZonesDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetTimeZoneFn(e);
    }
}

void ui_event_DaylightCorrCb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetDaylightOffsetFn(e);
    }
}

void ui_event_WirelessSetupBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFi, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFi_screen_init);
    }
}

void ui_event_MaxSleepTimeCtrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetSleepMaxTime(e);
    }
}

void ui_event_KeepOnWithChargerCb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetSleepWithChargerOpt(e);
    }
}

void ui_event_ExecCalBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_ExecCalLbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFi, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFi_screen_init);
    }
}

void ui_event_BatteryProtectionCb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetBatteryProtectionOpt(e);
    }
}

// build funtions

void ui_MoreOptions_screen_init(void)
{
    ui_MoreOptions = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MoreOptions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalListLbl = lv_label_create(ui_MoreOptions);
    lv_obj_set_width(ui_CalListLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_CalListLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalListLbl, -121);
    lv_obj_set_y(ui_CalListLbl, 20);
    lv_obj_set_align(ui_CalListLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalListLbl, "Calibrate:");

    ui_CalListDn = lv_dropdown_create(ui_MoreOptions);
    lv_dropdown_set_options(ui_CalListDn, "Vdiff\nIsense\nVdrive\nIdrive\nVbatt\nAll\nAuto");
    lv_obj_set_width(ui_CalListDn, 118);
    lv_obj_set_height(ui_CalListDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalListDn, -21);
    lv_obj_set_y(ui_CalListDn, 21);
    lv_obj_set_align(ui_CalListDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalListDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_CalListDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoreOptionsRetBtn = lv_btn_create(ui_MoreOptions);
    lv_obj_set_width(ui_MoreOptionsRetBtn, 60);
    lv_obj_set_height(ui_MoreOptionsRetBtn, 35);
    lv_obj_set_x(ui_MoreOptionsRetBtn, 127);
    lv_obj_set_y(ui_MoreOptionsRetBtn, 65);
    lv_obj_set_align(ui_MoreOptionsRetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoreOptionsRetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoreOptionsRetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MoreOptionsRetLbl = lv_label_create(ui_MoreOptionsRetBtn);
    lv_obj_set_width(ui_MoreOptionsRetLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoreOptionsRetLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MoreOptionsRetLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoreOptionsRetLbl, "Return");

    ui_TimeZoneLbl = lv_label_create(ui_MoreOptions);
    lv_obj_set_width(ui_TimeZoneLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_TimeZoneLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeZoneLbl, -120);
    lv_obj_set_y(ui_TimeZoneLbl, -65);
    lv_obj_set_align(ui_TimeZoneLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeZoneLbl, "TimeZone:");

    ui_TimeZonesDn = lv_dropdown_create(ui_MoreOptions);
    lv_dropdown_set_dir(ui_TimeZonesDn, LV_DIR_RIGHT);
    lv_dropdown_set_options(ui_TimeZonesDn,
                            "-12\n-11\n-10 \n-9\n-8 [US-PAC]\n-7\n-6\n-5 [US-EST]\n-4\n-3\n-2\n-1\n0 [UK]\n1 [CET]\n2\n3\n4\n5\n6\n7\n8 [CHN]\n9 [JPN]\n10\n11\n12");
    lv_obj_set_width(ui_TimeZonesDn, 116);
    lv_obj_set_height(ui_TimeZonesDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeZonesDn, -21);
    lv_obj_set_y(ui_TimeZonesDn, -64);
    lv_obj_set_align(ui_TimeZonesDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeZonesDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_TimeZonesDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DaylightCorrCb = lv_checkbox_create(ui_MoreOptions);
    lv_checkbox_set_text(ui_DaylightCorrCb, "Daylight Offset");
    lv_obj_set_width(ui_DaylightCorrCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DaylightCorrCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DaylightCorrCb, -88);
    lv_obj_set_y(ui_DaylightCorrCb, -36);
    lv_obj_set_align(ui_DaylightCorrCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DaylightCorrCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_WirelessSetupBtn = lv_btn_create(ui_MoreOptions);
    lv_obj_set_height(ui_WirelessSetupBtn, 35);
    lv_obj_set_width(ui_WirelessSetupBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_WirelessSetupBtn, 101);
    lv_obj_set_y(ui_WirelessSetupBtn, -65);
    lv_obj_set_align(ui_WirelessSetupBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WirelessSetupBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WirelessSetupBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_WirelessSetupBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WirelessSetupBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WirelessSetupBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WirelessSetupBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoreOptionsLbl = lv_label_create(ui_WirelessSetupBtn);
    lv_obj_set_width(ui_MoreOptionsLbl, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_MoreOptionsLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MoreOptionsLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoreOptionsLbl, "Wireless Setup");
    lv_obj_set_style_text_align(ui_MoreOptionsLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxSleepTimeCtrl = lv_slider_create(ui_MoreOptions);
    lv_slider_set_range(ui_MaxSleepTimeCtrl, 1, 36);
    lv_slider_set_value(ui_MaxSleepTimeCtrl, 6, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MaxSleepTimeCtrl) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MaxSleepTimeCtrl, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_MaxSleepTimeCtrl, 230);
    lv_obj_set_height(ui_MaxSleepTimeCtrl, 15);
    lv_obj_set_x(ui_MaxSleepTimeCtrl, -36);
    lv_obj_set_y(ui_MaxSleepTimeCtrl, 72);
    lv_obj_set_align(ui_MaxSleepTimeCtrl, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MaxSleepTimeCtrl, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MaxSleepTimeCtrl, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MaxSleepTimeCtrl, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MaxSleepTimeCtrl, lv_color_hex(0x130AE9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MaxSleepTimeCtrl, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MaxSleepTimeCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MaxSleepTimeCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MaxSleepTimeCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MaxSleepTimeCtrl, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MaxSleepTimeLbl = lv_label_create(ui_MoreOptions);
    lv_obj_set_width(ui_MaxSleepTimeLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_MaxSleepTimeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxSleepTimeLbl, -69);
    lv_obj_set_y(ui_MaxSleepTimeLbl, 50);
    lv_obj_set_align(ui_MaxSleepTimeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxSleepTimeLbl, "Max Time in Sleep [6Hr]");

    ui_KeepOnWithChargerCb = lv_checkbox_create(ui_MoreOptions);
    lv_checkbox_set_text(ui_KeepOnWithChargerCb, "Sleep with Charger");
    lv_obj_set_width(ui_KeepOnWithChargerCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeepOnWithChargerCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeepOnWithChargerCb, 72);
    lv_obj_set_y(ui_KeepOnWithChargerCb, -11);
    lv_obj_set_align(ui_KeepOnWithChargerCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeepOnWithChargerCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ExecCalBtn = lv_btn_create(ui_MoreOptions);
    lv_obj_set_width(ui_ExecCalBtn, 60);
    lv_obj_set_height(ui_ExecCalBtn, 35);
    lv_obj_set_x(ui_ExecCalBtn, 75);
    lv_obj_set_y(ui_ExecCalBtn, 20);
    lv_obj_set_align(ui_ExecCalBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ExecCalBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ExecCalBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExecCalLbl = lv_label_create(ui_ExecCalBtn);
    lv_obj_set_width(ui_ExecCalLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExecCalLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ExecCalLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExecCalLbl, "GO");

    ui_BatteryProtectionCb = lv_checkbox_create(ui_MoreOptions);
    lv_checkbox_set_text(ui_BatteryProtectionCb, "Protect Battery");
    lv_obj_set_width(ui_BatteryProtectionCb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryProtectionCb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryProtectionCb, -87);
    lv_obj_set_y(ui_BatteryProtectionCb, -11);
    lv_obj_set_align(ui_BatteryProtectionCb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryProtectionCb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_MoreOptionsRetLbl, ui_event_MoreOptionsRetLbl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoreOptionsRetBtn, ui_event_MoreOptionsRetBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeZonesDn, ui_event_TimeZonesDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DaylightCorrCb, ui_event_DaylightCorrCb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WirelessSetupBtn, ui_event_WirelessSetupBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MaxSleepTimeCtrl, ui_event_MaxSleepTimeCtrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeepOnWithChargerCb, ui_event_KeepOnWithChargerCb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ExecCalLbl, ui_event_ExecCalLbl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ExecCalBtn, ui_event_ExecCalBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BatteryProtectionCb, ui_event_BatteryProtectionCb, LV_EVENT_ALL, NULL);

}

void ui_MoreOptions_screen_destroy(void)
{
    if(ui_MoreOptions) lv_obj_del(ui_MoreOptions);

    // NULL screen variables
    ui_MoreOptions = NULL;
    ui_CalListLbl = NULL;
    ui_CalListDn = NULL;
    ui_MoreOptionsRetBtn = NULL;
    ui_MoreOptionsRetLbl = NULL;
    ui_TimeZoneLbl = NULL;
    ui_TimeZonesDn = NULL;
    ui_DaylightCorrCb = NULL;
    ui_WirelessSetupBtn = NULL;
    ui_MoreOptionsLbl = NULL;
    ui_MaxSleepTimeCtrl = NULL;
    ui_MaxSleepTimeLbl = NULL;
    ui_KeepOnWithChargerCb = NULL;
    ui_ExecCalBtn = NULL;
    ui_ExecCalLbl = NULL;
    ui_BatteryProtectionCb = NULL;

}
