// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern void ui_event_MainPageTabs(lv_event_t * e);
extern lv_obj_t * ui_MainPageTabs;
extern lv_obj_t * ui_VoltPage;
extern void ui_event_PeakBtn(lv_event_t * e);
extern lv_obj_t * ui_PeakBtn;
extern lv_obj_t * ui_PeakLbl;
extern void ui_event_HoldBtn(lv_event_t * e);
extern lv_obj_t * ui_HoldBtn;
extern lv_obj_t * ui_HldLbl;
extern lv_obj_t * ui_MinMeasVal;
extern lv_obj_t * ui_MinMeasLbl;
extern lv_obj_t * ui_MaxMeasLbl;
extern lv_obj_t * ui_MaxMeasVal;
extern lv_obj_t * ui_AverageMeasVal;
extern void ui_event_VinDividerBox(lv_event_t * e);
extern lv_obj_t * ui_VinDividerBox;
extern lv_obj_t * ui_VdiffMeasVal;
extern void ui_event_VdispGraphSelBtn(lv_event_t * e);
extern lv_obj_t * ui_VdispGraphSelBtn;
extern lv_obj_t * ui_AverageMeasLbl;
extern void ui_event_RelBtn(lv_event_t * e);
extern lv_obj_t * ui_RelBtn;
extern lv_obj_t * ui_RelLbl;
extern void ui_event_MorevBtn(lv_event_t * e);
extern lv_obj_t * ui_MorevBtn;
extern lv_obj_t * ui_MorevLbl;
extern lv_obj_t * ui_VdiffSignLbl;
extern lv_obj_t * ui_VdiffRngLbl;
extern lv_obj_t * ui_VdiffBarVal;
extern lv_obj_t * ui_BarGraphScaleImg;
extern lv_obj_t * ui_VoltRangeLbl;
extern void ui_event_VoltRangeDn(lv_event_t * e);
extern lv_obj_t * ui_VoltRangeDn;
extern lv_obj_t * ui_OhmPage;
extern lv_obj_t * ui_OhmMeasVal;
extern void ui_event_OhmSelDn(lv_event_t * e);
extern lv_obj_t * ui_OhmSelDn;
extern void ui_event_OhmModeCb(lv_event_t * e);
extern lv_obj_t * ui_OhmModeCb;
extern lv_obj_t * ui_OhmTrigBtn;
extern lv_obj_t * ui_OhmTrigLbl;
extern lv_obj_t * ui_OhmVLimitVal;
extern lv_obj_t * ui_OhmILimitVal;
extern void ui_event_OhmBuzzBtn(lv_event_t * e);
extern lv_obj_t * ui_OhmBuzzBtn;
extern lv_obj_t * ui_DiodeModeLbl1;
extern lv_obj_t * ui_DiodePage;
extern void ui_event_DiodeVfSelDn(lv_event_t * e);
extern lv_obj_t * ui_DiodeVfSelDn;
extern lv_obj_t * ui_DiodeVfVal;
extern lv_obj_t * ui_DiodeModeLbl;
extern lv_obj_t * ui_VdiodeLimitVal;
extern lv_obj_t * ui_IdiodeLimitVal;
extern lv_obj_t * ui_DiodeTrigBtn;
extern lv_obj_t * ui_VdTrigLbl;
extern void ui_event_DiodeMeasModeCb(lv_event_t * e);
extern lv_obj_t * ui_DiodeMeasModeCb;
extern void ui_event_DiodeBuzzBtn(lv_event_t * e);
extern lv_obj_t * ui_DiodeBuzzBtn;
extern lv_obj_t * ui_SMUPage;
extern lv_obj_t * ui_VoltgeRT;
extern lv_obj_t * ui_SMUVoltLbl;
extern void ui_event_VoltLimitSpin(lv_event_t * e);
extern lv_obj_t * ui_VoltLimitSpin;
extern lv_obj_t * ui_VLIMLbl;
extern void ui_event_CurrLimitSpin(lv_event_t * e);
extern lv_obj_t * ui_CurrLimitSpin;
extern lv_obj_t * ui_ILIMLbl;
extern lv_obj_t * ui_CurrentRT;
extern lv_obj_t * ui_SMUmALbl;
extern void ui_event_SMUOnOffBtn(lv_event_t * e);
extern lv_obj_t * ui_SMUOnOffBtn;
extern lv_obj_t * ui_SMUOnOffLbl;
extern lv_obj_t * ui_Options;
extern void ui_event_FlipDispCntrl(lv_event_t * e);
extern lv_obj_t * ui_FlipDispCntrl;
extern void ui_event_StandbyOptDn(lv_event_t * e);
extern lv_obj_t * ui_StandbyOptDn;
extern lv_obj_t * ui_StandbyLbl;
extern void ui_event_MaxBrightnessCtrl(lv_event_t * e);
extern lv_obj_t * ui_MaxBrightnessCtrl;
extern lv_obj_t * ui_MaxBrightnessLbl;
extern void ui_event_MinBrightnessCtrl(lv_event_t * e);
extern lv_obj_t * ui_MinBrightnessCtrl;
extern lv_obj_t * ui_MinBrightnessLbl;
extern void ui_event_BacklightToutCtrl(lv_event_t * e);
extern lv_obj_t * ui_BacklightToutCtrl;
extern lv_obj_t * ui_BacklightToutLbl;
extern void ui_event_MoreOptionsBtn(lv_event_t * e);
extern lv_obj_t * ui_MoreOptionsBtn;
extern lv_obj_t * ui_CalibrationsLbl;
extern lv_obj_t * ui_timeInfo;
extern lv_obj_t * ui_ESPNOW;
extern lv_obj_t * ui_WifiImg;
extern lv_obj_t * ui_SysInfoLbl;
extern void ui_event_BattInf(lv_event_t * e);
extern lv_obj_t * ui_BattInf;
extern lv_obj_t * ui_BattLevLbl;
extern lv_obj_t * ui_ChargingImg;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CurrentRT;
extern lv_obj_t * uic_CalibrationsLbl;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

