// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * ui_Volt_More = NULL;
lv_obj_t * ui_VprobeGainSelectDn = NULL;
lv_obj_t * ui_VprobeGainSelectMainLbl = NULL;
lv_obj_t * ui_VdiffGainSelectDn = NULL;
lv_obj_t * ui_VdiffGainSelectMainLbl = NULL;
lv_obj_t * ui_GainSelectMainLbl = NULL;
lv_obj_t * ui_AverageMainLbl = NULL;
lv_obj_t * ui_pVnPLbl = NULL;
lv_obj_t * ui_nVnNLbl = NULL;
lv_obj_t * ui_VbattLbl = NULL;
lv_obj_t * ui_pVdiffVal = NULL;
lv_obj_t * ui_nVdiffVal = NULL;
lv_obj_t * ui_VBattVal = NULL;
lv_obj_t * ui_IsnsLbl = NULL;
lv_obj_t * ui_IsnsVal = NULL;
lv_obj_t * ui_VdrvLbl = NULL;
lv_obj_t * ui_VDrvVal = NULL;
lv_obj_t * ui_IdrvLbl = NULL;
lv_obj_t * ui_IDrvVal = NULL;
lv_obj_t * ui_RetVoltBtn = NULL;
lv_obj_t * ui_RetVoltLbl = NULL;
lv_obj_t * ui_SampleRateLbl = NULL;
lv_obj_t * ui_SampleRateDn = NULL;
lv_obj_t * ui_SampleAvgDn = NULL;
// event funtions
void ui_event_VprobeGainSelectDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetVnP_GainFn(e);
    }
}

void ui_event_VdiffGainSelectDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetVdiff_GainFn(e);
    }
}

void ui_event_RetVoltBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_SampleRateDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetADC_SampleRateFn(e);
    }
}

void ui_event_SampleAvgDn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetADC_NumAvgFn(e);
    }
}

// build funtions

void ui_Volt_More_screen_init(void)
{
    ui_Volt_More = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Volt_More, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Volt_More, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volt_More, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VprobeGainSelectDn = lv_dropdown_create(ui_Volt_More);
    lv_dropdown_set_options(ui_VprobeGainSelectDn, "x1\nx2\nx4\nx8\nx16\nx32\nx64\nx128");
    lv_obj_set_width(ui_VprobeGainSelectDn, 66);
    lv_obj_set_height(ui_VprobeGainSelectDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VprobeGainSelectDn, -120);
    lv_obj_set_y(ui_VprobeGainSelectDn, -28);
    lv_obj_set_align(ui_VprobeGainSelectDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VprobeGainSelectDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_VprobeGainSelectDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VprobeGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VprobeGainSelectDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VprobeGainSelectDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VprobeGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VprobeGainSelectDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VprobeGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VprobeGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VprobeGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VprobeGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VprobeGainSelectDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VprobeGainSelectDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_VprobeGainSelectDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_VprobeGainSelectDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VprobeGainSelectMainLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VprobeGainSelectMainLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VprobeGainSelectMainLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VprobeGainSelectMainLbl, -70);
    lv_obj_set_y(ui_VprobeGainSelectMainLbl, -28);
    lv_obj_set_align(ui_VprobeGainSelectMainLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VprobeGainSelectMainLbl, "VnP");
    lv_obj_set_style_text_color(ui_VprobeGainSelectMainLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VprobeGainSelectMainLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiffGainSelectDn = lv_dropdown_create(ui_Volt_More);
    lv_dropdown_set_options(ui_VdiffGainSelectDn, "x1\nx2\nx4\nx8\nx16\nx32\nx64\nx128");
    lv_obj_set_width(ui_VdiffGainSelectDn, 66);
    lv_obj_set_height(ui_VdiffGainSelectDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiffGainSelectDn, -120);
    lv_obj_set_y(ui_VdiffGainSelectDn, -57);
    lv_obj_set_align(ui_VdiffGainSelectDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VdiffGainSelectDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_VdiffGainSelectDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiffGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VdiffGainSelectDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VdiffGainSelectDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VdiffGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VdiffGainSelectDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VdiffGainSelectDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VdiffGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VdiffGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VdiffGainSelectDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VdiffGainSelectDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VdiffGainSelectDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_VdiffGainSelectDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_VdiffGainSelectDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdiffGainSelectMainLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VdiffGainSelectMainLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdiffGainSelectMainLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdiffGainSelectMainLbl, -68);
    lv_obj_set_y(ui_VdiffGainSelectMainLbl, -57);
    lv_obj_set_align(ui_VdiffGainSelectMainLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VdiffGainSelectMainLbl, "Vdiff");
    lv_obj_set_style_text_color(ui_VdiffGainSelectMainLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdiffGainSelectMainLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GainSelectMainLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_GainSelectMainLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GainSelectMainLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GainSelectMainLbl, -137);
    lv_obj_set_y(ui_GainSelectMainLbl, -78);
    lv_obj_set_align(ui_GainSelectMainLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GainSelectMainLbl, "Gain");
    lv_obj_set_style_text_color(ui_GainSelectMainLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GainSelectMainLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AverageMainLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_AverageMainLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AverageMainLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AverageMainLbl, -120);
    lv_obj_set_y(ui_AverageMainLbl, -2);
    lv_obj_set_align(ui_AverageMainLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AverageMainLbl, "Averages");
    lv_obj_set_style_text_color(ui_AverageMainLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AverageMainLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pVnPLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_pVnPLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pVnPLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pVnPLbl, -12);
    lv_obj_set_y(ui_pVnPLbl, -75);
    lv_obj_set_align(ui_pVnPLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pVnPLbl, "+Vn:");
    lv_obj_set_style_text_color(ui_pVnPLbl, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pVnPLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pVnPLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nVnNLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_nVnNLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nVnNLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nVnNLbl, -10);
    lv_obj_set_y(ui_nVnNLbl, -54);
    lv_obj_set_align(ui_nVnNLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nVnNLbl, "-Vn:");
    lv_obj_set_style_text_color(ui_nVnNLbl, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nVnNLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nVnNLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VbattLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VbattLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VbattLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VbattLbl, -20);
    lv_obj_set_y(ui_VbattLbl, 36);
    lv_obj_set_align(ui_VbattLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VbattLbl, "VBatt:");
    lv_obj_set_style_text_color(ui_VbattLbl, lv_color_hex(0x080EF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VbattLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VbattLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pVdiffVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_pVdiffVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pVdiffVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pVdiffVal, 63);
    lv_obj_set_y(ui_pVdiffVal, -73);
    lv_obj_set_align(ui_pVdiffVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pVdiffVal, "+00.000V");
    lv_obj_set_style_text_color(ui_pVdiffVal, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pVdiffVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pVdiffVal, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nVdiffVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_nVdiffVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nVdiffVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nVdiffVal, 63);
    lv_obj_set_y(ui_nVdiffVal, -52);
    lv_obj_set_align(ui_nVdiffVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nVdiffVal, "+00.000V");
    lv_obj_set_style_text_color(ui_nVdiffVal, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nVdiffVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nVdiffVal, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VBattVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VBattVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VBattVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VBattVal, 56);
    lv_obj_set_y(ui_VBattVal, 38);
    lv_obj_set_align(ui_VBattVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VBattVal, "+0.000V");
    lv_obj_set_style_text_color(ui_VBattVal, lv_color_hex(0x080EF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VBattVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VBattVal, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsnsLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_IsnsLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsnsLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IsnsLbl, -12);
    lv_obj_set_y(ui_IsnsLbl, 14);
    lv_obj_set_align(ui_IsnsLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IsnsLbl, "Isns:");
    lv_obj_set_style_text_color(ui_IsnsLbl, lv_color_hex(0xB019C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IsnsLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IsnsLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IsnsVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_IsnsVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IsnsVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IsnsVal, 83);
    lv_obj_set_y(ui_IsnsVal, 16);
    lv_obj_set_align(ui_IsnsVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IsnsVal, "+000.000mA");
    lv_obj_set_style_text_color(ui_IsnsVal, lv_color_hex(0xB019C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IsnsVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IsnsVal, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VdrvLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VdrvLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VdrvLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VdrvLbl, -15);
    lv_obj_set_y(ui_VdrvLbl, -32);
    lv_obj_set_align(ui_VdrvLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VdrvLbl, "Vdrv:");
    lv_obj_set_style_text_color(ui_VdrvLbl, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VdrvLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VdrvLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VDrvVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_VDrvVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VDrvVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VDrvVal, 63);
    lv_obj_set_y(ui_VDrvVal, -30);
    lv_obj_set_align(ui_VDrvVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VDrvVal, "+00.000V");
    lv_obj_set_style_text_color(ui_VDrvVal, lv_color_hex(0x08F8F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VDrvVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VDrvVal, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IdrvLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_IdrvLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IdrvLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IdrvLbl, -12);
    lv_obj_set_y(ui_IdrvLbl, -10);
    lv_obj_set_align(ui_IdrvLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IdrvLbl, "Idrv:");
    lv_obj_set_style_text_color(ui_IdrvLbl, lv_color_hex(0xB019C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IdrvLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IdrvLbl, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDrvVal = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_IDrvVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDrvVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDrvVal, 83);
    lv_obj_set_y(ui_IDrvVal, -8);
    lv_obj_set_align(ui_IDrvVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IDrvVal, "+000.000mA");
    lv_obj_set_style_text_color(ui_IDrvVal, lv_color_hex(0xB019C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDrvVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IDrvVal, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetVoltBtn = lv_btn_create(ui_Volt_More);
    lv_obj_set_width(ui_RetVoltBtn, 64);
    lv_obj_set_height(ui_RetVoltBtn, 29);
    lv_obj_set_x(ui_RetVoltBtn, 126);
    lv_obj_set_y(ui_RetVoltBtn, 67);
    lv_obj_set_align(ui_RetVoltBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RetVoltBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RetVoltBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RetVoltBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RetVoltBtn, lv_color_hex(0x837F83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RetVoltBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RetVoltBtn, lv_color_hex(0xB0B0EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RetVoltBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RetVoltBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RetVoltBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RetVoltLbl = lv_label_create(ui_RetVoltBtn);
    lv_obj_set_width(ui_RetVoltLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RetVoltLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RetVoltLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RetVoltLbl, "RET.");
    lv_obj_set_style_text_color(ui_RetVoltLbl, lv_color_hex(0xE8FAE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RetVoltLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SampleRateLbl = lv_label_create(ui_Volt_More);
    lv_obj_set_width(ui_SampleRateLbl, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_SampleRateLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SampleRateLbl, -130);
    lv_obj_set_y(ui_SampleRateLbl, 44);
    lv_obj_set_align(ui_SampleRateLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SampleRateLbl, "Smp/s");
    lv_obj_set_style_text_color(ui_SampleRateLbl, lv_color_hex(0x22D6FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SampleRateLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SampleRateDn = lv_dropdown_create(ui_Volt_More);
    lv_dropdown_set_options(ui_SampleRateDn, "20\n45\n90\n175\n330\n600\n1000\n2000");
    lv_obj_set_width(ui_SampleRateDn, 66);
    lv_obj_set_height(ui_SampleRateDn, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_SampleRateDn, -120);
    lv_obj_set_y(ui_SampleRateDn, 66);
    lv_obj_set_align(ui_SampleRateDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SampleRateDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_SampleRateDn, lv_color_hex(0xE6FA04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SampleRateDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SampleRateDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SampleRateDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SampleRateDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SampleRateDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SampleRateDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SampleRateDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SampleRateDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SampleRateDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SampleRateDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SampleRateDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SampleRateDn, lv_color_hex(0xF6F116), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SampleRateDn, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_SampleRateDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_SampleRateDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SampleAvgDn = lv_dropdown_create(ui_Volt_More);
    lv_dropdown_set_options(ui_SampleAvgDn, "x1\nx2\nx4\nx8\nx16\nx32\nx64\nx128\nx256");
    lv_obj_set_width(ui_SampleAvgDn, 66);
    lv_obj_set_height(ui_SampleAvgDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SampleAvgDn, -120);
    lv_obj_set_y(ui_SampleAvgDn, 21);
    lv_obj_set_align(ui_SampleAvgDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SampleAvgDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_SampleAvgDn, lv_color_hex(0xEDF911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SampleAvgDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SampleAvgDn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SampleAvgDn, lv_color_hex(0x1C5D60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SampleAvgDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SampleAvgDn, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SampleAvgDn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SampleAvgDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SampleAvgDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SampleAvgDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SampleAvgDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SampleAvgDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_SampleAvgDn), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_SampleAvgDn), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VprobeGainSelectDn, ui_event_VprobeGainSelectDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VdiffGainSelectDn, ui_event_VdiffGainSelectDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RetVoltBtn, ui_event_RetVoltBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SampleRateDn, ui_event_SampleRateDn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SampleAvgDn, ui_event_SampleAvgDn, LV_EVENT_ALL, NULL);

}

void ui_Volt_More_screen_destroy(void)
{
    if(ui_Volt_More) lv_obj_del(ui_Volt_More);

    // NULL screen variables
    ui_Volt_More = NULL;
    ui_VprobeGainSelectDn = NULL;
    ui_VprobeGainSelectMainLbl = NULL;
    ui_VdiffGainSelectDn = NULL;
    ui_VdiffGainSelectMainLbl = NULL;
    ui_GainSelectMainLbl = NULL;
    ui_AverageMainLbl = NULL;
    ui_pVnPLbl = NULL;
    ui_nVnNLbl = NULL;
    ui_VbattLbl = NULL;
    ui_pVdiffVal = NULL;
    ui_nVdiffVal = NULL;
    ui_VBattVal = NULL;
    ui_IsnsLbl = NULL;
    ui_IsnsVal = NULL;
    ui_VdrvLbl = NULL;
    ui_VDrvVal = NULL;
    ui_IdrvLbl = NULL;
    ui_IDrvVal = NULL;
    ui_RetVoltBtn = NULL;
    ui_RetVoltLbl = NULL;
    ui_SampleRateLbl = NULL;
    ui_SampleRateDn = NULL;
    ui_SampleAvgDn = NULL;

}
