// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_VOLT_MORE_H
#define UI_VOLT_MORE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Volt_More
extern void ui_Volt_More_screen_init(void);
extern void ui_Volt_More_screen_destroy(void);
extern lv_obj_t * ui_Volt_More;
extern void ui_event_VprobeGainSelectDn(lv_event_t * e);
extern lv_obj_t * ui_VprobeGainSelectDn;
extern lv_obj_t * ui_VprobeGainSelectMainLbl;
extern void ui_event_VdiffGainSelectDn(lv_event_t * e);
extern lv_obj_t * ui_VdiffGainSelectDn;
extern lv_obj_t * ui_VdiffGainSelectMainLbl;
extern lv_obj_t * ui_GainSelectMainLbl;
extern lv_obj_t * ui_AverageMainLbl;
extern lv_obj_t * ui_pVnPLbl;
extern lv_obj_t * ui_nVnNLbl;
extern lv_obj_t * ui_VbattLbl;
extern lv_obj_t * ui_pVdiffVal;
extern lv_obj_t * ui_nVdiffVal;
extern lv_obj_t * ui_VBattVal;
extern lv_obj_t * ui_IsnsLbl;
extern lv_obj_t * ui_IsnsVal;
extern lv_obj_t * ui_VdrvLbl;
extern lv_obj_t * ui_VDrvVal;
extern lv_obj_t * ui_IdrvLbl;
extern lv_obj_t * ui_IDrvVal;
extern void ui_event_RetVoltBtn(lv_event_t * e);
extern lv_obj_t * ui_RetVoltBtn;
extern lv_obj_t * ui_RetVoltLbl;
extern lv_obj_t * ui_SampleRateLbl;
extern void ui_event_SampleRateDn(lv_event_t * e);
extern lv_obj_t * ui_SampleRateDn;
extern void ui_event_SampleAvgDn(lv_event_t * e);
extern lv_obj_t * ui_SampleAvgDn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

