// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#include "../ui.h"

lv_obj_t * ui_WiFi = NULL;
lv_obj_t * ui_WiFiStatusLbl = NULL;
lv_obj_t * ui_WiFiReturnBtn = NULL;
lv_obj_t * ui_WiFiRetLbl = NULL;
lv_obj_t * ui_DeviceMACAddrLbl = NULL;
lv_obj_t * ui_SSIDLbl = NULL;
lv_obj_t * ui_WiFiScanBtn = NULL;
lv_obj_t * ui_WiFiScanLbl = NULL;
lv_obj_t * ui_SSIDListDn = NULL;
lv_obj_t * ui_WiFiConnectBtn = NULL;
lv_obj_t * ui_WiFiConnectLbl = NULL;
lv_obj_t * ui_PasswordArea = NULL;
lv_obj_t * ui_PWDLbl = NULL;
lv_obj_t * ui_PwdEntryKb = NULL;
lv_obj_t * ui_RemoteMACAddrLbl = NULL;
lv_obj_t * ui_DeviceMACLbl = NULL;
lv_obj_t * ui_RemoteMACLbl = NULL;
// event funtions
void ui_event_WiFiReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_WiFiScanBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ScanWiFiNetwork(e);
    }
}

void ui_event_WiFiConnectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ConnectWiFiNetwork(e);
    }
}

void ui_event_PasswordArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        KeybOnAn_Animation(ui_PwdEntryKb, 0);
    }
}

void ui_event_PwdEntryKb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        KeybOffAn_Animation(ui_PwdEntryKb, 0);
    }
}

// build funtions

void ui_WiFi_screen_init(void)
{
    ui_WiFi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiStatusLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_WiFiStatusLbl, 229);
    lv_obj_set_height(ui_WiFiStatusLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusLbl, 38);
    lv_obj_set_y(ui_WiFiStatusLbl, -9);
    lv_obj_set_align(ui_WiFiStatusLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiStatusLbl, "Status:");
    lv_obj_set_style_border_color(ui_WiFiStatusLbl, lv_color_hex(0xA79E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiStatusLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WiFiStatusLbl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WiFiStatusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WiFiStatusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WiFiStatusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WiFiStatusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiReturnBtn = lv_btn_create(ui_WiFi);
    lv_obj_set_width(ui_WiFiReturnBtn, 60);
    lv_obj_set_height(ui_WiFiReturnBtn, 35);
    lv_obj_set_x(ui_WiFiReturnBtn, 127);
    lv_obj_set_y(ui_WiFiReturnBtn, 65);
    lv_obj_set_align(ui_WiFiReturnBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiReturnBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiReturnBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiRetLbl = lv_label_create(ui_WiFiReturnBtn);
    lv_obj_set_width(ui_WiFiRetLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiRetLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiRetLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiRetLbl, "Return");

    ui_DeviceMACAddrLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_DeviceMACAddrLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceMACAddrLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceMACAddrLbl, -51);
    lv_obj_set_y(ui_DeviceMACAddrLbl, 33);
    lv_obj_set_align(ui_DeviceMACAddrLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceMACAddrLbl, "MAC Addr: FF:FF:FF:FF:FF:FF");
    lv_obj_set_style_text_color(ui_DeviceMACAddrLbl, lv_color_hex(0x0D13E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeviceMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeviceMACAddrLbl, lv_color_hex(0xF3F9E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeviceMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DeviceMACAddrLbl, lv_color_hex(0xA79E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DeviceMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeviceMACAddrLbl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DeviceMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DeviceMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DeviceMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DeviceMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_SSIDLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_SSIDLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDLbl, -136);
    lv_obj_set_y(ui_SSIDLbl, -69);
    lv_obj_set_align(ui_SSIDLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLbl, "SSID:");

    ui_WiFiScanBtn = lv_btn_create(ui_WiFi);
    lv_obj_set_height(ui_WiFiScanBtn, 28);
    lv_obj_set_width(ui_WiFiScanBtn, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_x(ui_WiFiScanBtn, 132);
    lv_obj_set_y(ui_WiFiScanBtn, -69);
    lv_obj_set_align(ui_WiFiScanBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiScanBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiScanBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_WiFiScanBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WiFiScanBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WiFiScanBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WiFiScanBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiScanLbl = lv_label_create(ui_WiFiScanBtn);
    lv_obj_set_width(ui_WiFiScanLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiScanLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiScanLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiScanLbl, "SCAN");

    ui_SSIDListDn = lv_dropdown_create(ui_WiFi);
    lv_dropdown_set_options(ui_SSIDListDn, "DLCompZ\nDLCompZ2G\nDLCompZ2G_R");
    lv_obj_set_width(ui_SSIDListDn, 205);
    lv_obj_set_height(ui_SSIDListDn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDListDn, -7);
    lv_obj_set_y(ui_SSIDListDn, -69);
    lv_obj_set_align(ui_SSIDListDn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SSIDListDn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_SSIDListDn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SSIDListDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SSIDListDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SSIDListDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SSIDListDn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnectBtn = lv_btn_create(ui_WiFi);
    lv_obj_set_height(ui_WiFiConnectBtn, 23);
    lv_obj_set_width(ui_WiFiConnectBtn, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_x(ui_WiFiConnectBtn, -119);
    lv_obj_set_y(ui_WiFiConnectBtn, -10);
    lv_obj_set_align(ui_WiFiConnectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_WiFiConnectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WiFiConnectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WiFiConnectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WiFiConnectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnectLbl = lv_label_create(ui_WiFiConnectBtn);
    lv_obj_set_width(ui_WiFiConnectLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiConnectLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiConnectLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiConnectLbl, "CONNECT");

    ui_PasswordArea = lv_textarea_create(ui_WiFi);
    lv_obj_set_width(ui_PasswordArea, 204);
    lv_obj_set_height(ui_PasswordArea, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_PasswordArea, -7);
    lv_obj_set_y(ui_PasswordArea, -40);
    lv_obj_set_align(ui_PasswordArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordArea, "Enter Password...");
    lv_textarea_set_one_line(ui_PasswordArea, true);
    lv_textarea_set_password_mode(ui_PasswordArea, true);
    lv_obj_set_style_radius(ui_PasswordArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PasswordArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PasswordArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PasswordArea, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PasswordArea, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWDLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_PWDLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_PWDLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWDLbl, -134);
    lv_obj_set_y(ui_PWDLbl, -41);
    lv_obj_set_align(ui_PWDLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWDLbl, "PWD:");

    ui_PwdEntryKb = lv_keyboard_create(ui_WiFi);
    lv_obj_set_width(ui_PwdEntryKb, 314);
    lv_obj_set_height(ui_PwdEntryKb, 146);
    lv_obj_set_x(ui_PwdEntryKb, 0);
    lv_obj_set_y(ui_PwdEntryKb, 162);
    lv_obj_set_align(ui_PwdEntryKb, LV_ALIGN_CENTER);

    ui_RemoteMACAddrLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_RemoteMACAddrLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RemoteMACAddrLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemoteMACAddrLbl, -52);
    lv_obj_set_y(ui_RemoteMACAddrLbl, 73);
    lv_obj_set_align(ui_RemoteMACAddrLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RemoteMACAddrLbl, "MAC Addr: FF:FF:FF:FF:FF:FF");
    lv_obj_set_style_text_color(ui_RemoteMACAddrLbl, lv_color_hex(0x0D13E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RemoteMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RemoteMACAddrLbl, lv_color_hex(0xF3F9E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RemoteMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RemoteMACAddrLbl, lv_color_hex(0xA79E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RemoteMACAddrLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RemoteMACAddrLbl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RemoteMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RemoteMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RemoteMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RemoteMACAddrLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceMACLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_DeviceMACLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_DeviceMACLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceMACLbl, -128);
    lv_obj_set_y(ui_DeviceMACLbl, 16);
    lv_obj_set_align(ui_DeviceMACLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeviceMACLbl, "DEVICE:");

    ui_RemoteMACLbl = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_RemoteMACLbl, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_RemoteMACLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemoteMACLbl, -124);
    lv_obj_set_y(ui_RemoteMACLbl, 55);
    lv_obj_set_align(ui_RemoteMACLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RemoteMACLbl, "REMOTE:");

    lv_obj_add_event_cb(ui_WiFiReturnBtn, ui_event_WiFiReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiScanBtn, ui_event_WiFiScanBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiConnectBtn, ui_event_WiFiConnectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordArea, ui_event_PasswordArea, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PwdEntryKb, ui_PasswordArea);
    lv_obj_add_event_cb(ui_PwdEntryKb, ui_event_PwdEntryKb, LV_EVENT_ALL, NULL);

}

void ui_WiFi_screen_destroy(void)
{
    if(ui_WiFi) lv_obj_del(ui_WiFi);

    // NULL screen variables
    ui_WiFi = NULL;
    ui_WiFiStatusLbl = NULL;
    ui_WiFiReturnBtn = NULL;
    ui_WiFiRetLbl = NULL;
    ui_DeviceMACAddrLbl = NULL;
    ui_SSIDLbl = NULL;
    ui_WiFiScanBtn = NULL;
    ui_WiFiScanLbl = NULL;
    ui_SSIDListDn = NULL;
    ui_WiFiConnectBtn = NULL;
    ui_WiFiConnectLbl = NULL;
    ui_PasswordArea = NULL;
    ui_PWDLbl = NULL;
    ui_PwdEntryKb = NULL;
    ui_RemoteMACAddrLbl = NULL;
    ui_DeviceMACLbl = NULL;
    ui_RemoteMACLbl = NULL;

}
