// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SimpleESP32S3

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFi
extern void ui_WiFi_screen_init(void);
extern void ui_WiFi_screen_destroy(void);
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_WiFiStatusLbl;
extern void ui_event_WiFiReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_WiFiReturnBtn;
extern lv_obj_t * ui_WiFiRetLbl;
extern lv_obj_t * ui_DeviceMACAddrLbl;
extern lv_obj_t * ui_SSIDLbl;
extern void ui_event_WiFiScanBtn(lv_event_t * e);
extern lv_obj_t * ui_WiFiScanBtn;
extern lv_obj_t * ui_WiFiScanLbl;
extern lv_obj_t * ui_SSIDListDn;
extern void ui_event_WiFiConnectBtn(lv_event_t * e);
extern lv_obj_t * ui_WiFiConnectBtn;
extern lv_obj_t * ui_WiFiConnectLbl;
extern void ui_event_PasswordArea(lv_event_t * e);
extern lv_obj_t * ui_PasswordArea;
extern lv_obj_t * ui_PWDLbl;
extern void ui_event_PwdEntryKb(lv_event_t * e);
extern lv_obj_t * ui_PwdEntryKb;
extern lv_obj_t * ui_RemoteMACAddrLbl;
extern lv_obj_t * ui_DeviceMACLbl;
extern lv_obj_t * ui_RemoteMACLbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

